---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, NetApp Consolecloud manager 
summary: 콘솔은 Cloud Volumes ONTAP 스토리지의 간소화되고 고급화된 관리 기능을 제공합니다. 
---
= Cloud Volumes ONTAP 스토리지 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console Cloud Volumes ONTAP 스토리지에 대한 간편하고 고급 관리 기능을 제공합니다.


CAUTION: 모든 디스크와 집계는 콘솔에서 직접 만들고 삭제해야 합니다. 다른 관리 도구에서는 이러한 작업을 수행해서는 안 됩니다. 그렇게 하면 시스템 안정성에 영향을 미치고, 나중에 디스크를 추가하는 기능을 방해할 수 있으며, 잠재적으로 중복된 클라우드 공급자 수수료가 발생할 수 있습니다.



== 스토리지 프로비저닝

콘솔을 사용하면 디스크를 구매하고 집계를 관리하여 Cloud Volumes ONTAP 에 대한 스토리지 프로비저닝이 쉬워집니다.  볼륨만 생성하면 됩니다.  원하는 경우 고급 할당 옵션을 사용하여 직접 집계를 프로비저닝할 수 있습니다.



=== 간소화된 프로비저닝

집계는 볼륨에 클라우드 스토리지를 제공합니다.  콘솔은 인스턴스를 시작할 때와 추가 볼륨을 프로비저닝할 때 집계를 생성합니다.

볼륨을 생성하면 콘솔은 다음 세 가지 작업 중 하나를 수행합니다.

* 충분한 여유 공간이 있는 기존 집합체에 볼륨을 배치합니다.
* 해당 집계에 대해 추가 디스크를 구매하여 볼륨을 기존 집계에 배치합니다.


ifdef::aws[]

+ Elastic Volumes를 지원하는 AWS의 집계의 경우 RAID 그룹의 디스크 크기도 늘어납니다. link:concept-aws-elastic-volumes.html["Elastic Volumes 지원에 대해 자세히 알아보세요"] .

endif::aws[]

* 새로운 집계를 위해 디스크를 구매하고 해당 집계에 볼륨을 배치합니다.


콘솔은 집계의 최대 크기, 씬 프로비저닝이 활성화되어 있는지 여부, 집계의 여유 공간 임계값 등 여러 요소를 고려하여 새 볼륨을 배치할 위치를 결정합니다.

ifdef::aws[]



==== AWS의 집계를 위한 디스크 크기 선택

콘솔이 AWS에서 Cloud Volumes ONTAP 에 대한 새로운 집계를 생성할 때 집계 수가 증가함에 따라 디스크 크기를 점차 늘려 AWS 데이터 디스크 제한에 도달하기 전에 시스템 용량을 극대화합니다.

예를 들어, 콘솔은 다음과 같은 디스크 크기를 선택할 수 있습니다.

[cols="3*"]
|===
| 집계 번호 | 디스크 크기 | 최대 집계 용량 


| 1 | 500기가바이트 | 3티비 


| 4 | 1티비 | 6티비 


| 6 | 2티비 | 12티비 
|===

NOTE: 이 동작은 Amazon EBS Elastic Volumes 기능을 지원하는 집계에는 적용되지 않습니다.  탄력적 볼륨이 활성화된 집계는 하나 또는 두 개의 RAID 그룹으로 구성됩니다.  각 RAID 그룹에는 동일한 용량을 가진 4개의 동일한 디스크가 있습니다. link:concept-aws-elastic-volumes.html["Elastic Volumes 지원에 대해 자세히 알아보세요"] .

고급 할당 옵션을 사용하면 디스크 크기를 직접 선택할 수 있습니다.

endif::aws[]



=== 고급 할당

집계도 관리할 수 있습니다. link:task-create-aggregates.html["*고급 할당* 페이지에서"] , 특정 수의 디스크를 포함하는 새로운 집계를 만들고, 기존 집계에 디스크를 추가하고, 특정 집계에 볼륨을 만들 수 있습니다.



== 용량 관리

조직 또는 계정 관리자는 콘솔을 구성하여 저장 용량 결정 사항을 알리거나 자동으로 용량 요구 사항을 관리할지 여부를 결정할 수 있습니다.

이 동작은 콘솔 에이전트의 _용량 관리 모드_에 의해 결정됩니다.  용량 관리 모드는 해당 콘솔 에이전트가 관리하는 모든 Cloud Volumes ONTAP 시스템에 영향을 미칩니다.  다른 콘솔 에이전트가 있는 경우 다르게 구성할 수 있습니다.



=== 자동 용량 관리

용량 관리 모드는 기본적으로 자동으로 설정되어 있습니다.  이 모드에서는 콘솔이 15분마다 여유 공간 비율을 확인하여 여유 공간 비율이 지정된 임계값 아래로 떨어지는지 확인합니다.  더 많은 용량이 필요한 경우 새 디스크를 구매하고, 사용하지 않는 디스크 컬렉션(집계)을 삭제하고, 필요에 따라 집계 간에 볼륨을 이동하고, 디스크 오류를 방지하려고 시도합니다.

다음 예에서는 이 모드가 작동하는 방식을 보여줍니다.

* 집계가 용량 임계값에 도달하고 디스크를 더 추가할 공간이 있는 경우 콘솔은 자동으로 해당 집계에 대한 새 디스크를 구매하여 볼륨이 계속 증가할 수 있도록 합니다.
+
ifdef::aws[]



Elastic Volumes를 지원하는 AWS의 집계의 경우 RAID 그룹의 디스크 크기도 늘어납니다. link:concept-aws-elastic-volumes.html["Elastic Volumes 지원에 대해 자세히 알아보세요"] .

endif::aws[]

+ * 집계가 용량 임계값에 도달하여 추가 디스크를 지원할 수 없는 경우 콘솔은 자동으로 해당 집계의 볼륨을 사용 가능한 용량이 있는 집계나 새 집계로 이동합니다.

+ 콘솔이 볼륨에 대한 새로운 집계를 생성하는 경우 해당 볼륨의 크기에 맞는 디스크 크기를 선택합니다.

+ 원래 집계에서 이제 사용 가능한 공간이 생겼다는 점에 유의하세요.  기존 볼륨이나 새로운 볼륨이 해당 공간을 사용할 수 있습니다.  이 시나리오에서는 해당 공간을 클라우드 제공자에게 반환할 수 없습니다.

* 집계에 12시간 이상 볼륨이 없으면 콘솔에서 해당 집계를 삭제합니다.




==== 자동 용량 관리를 통한 LUN 관리

콘솔의 자동 용량 관리 기능은 LUN에 적용되지 않습니다.  LUN을 생성하면 자동 증가 기능이 비활성화됩니다.



=== 수동 용량 관리

조직 또는 계정 관리자가 용량 관리 모드를 수동으로 설정하면 콘솔에서 용량 결정에 대한 적절한 조치를 취하라는 메시지가 표시됩니다.  자동 모드에서 설명한 것과 동일한 예가 수동 모드에도 적용되지만, 작업을 수락하는 것은 사용자의 책임입니다.



=== 자세히 알아보기

link:task-manage-capacity-settings.html["용량 관리 모드를 수정하는 방법을 알아보세요"] .
