---
sidebar: sidebar 
permalink: concept-client-protocols.html 
keywords: client protocols, client version, smb version, nfs version, protocol versions, s3, smb, nfs, iscsi, cifs 
summary: Cloud Volumes ONTAP iSCSI, NFS, SMB, NVMe-TCP 및 S3 클라이언트 프로토콜을 지원합니다. 
---
= Cloud Volumes ONTAP 에 지원되는 클라이언트 프로토콜
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP iSCSI, NFS, SMB, NVMe-TCP 및 S3 클라이언트 프로토콜을 지원합니다.



== iSCSI

iSCSI는 표준 이더넷 네트워크에서 실행될 수 있는 블록 프로토콜입니다.  대부분의 클라이언트 운영 체제는 표준 이더넷 포트를 통해 실행되는 소프트웨어 개시 프로그램을 제공합니다.



== NFS

NFS는 UNIX와 LINUX 시스템을 위한 전통적인 파일 접근 프로토콜입니다.  클라이언트는 NFSv3, NFSv4 및 NFSv4.1 프로토콜을 사용하여 ONTAP 볼륨의 파일에 액세스할 수 있습니다.  UNIX 스타일 권한, NTFS 스타일 권한 또는 두 가지를 혼합하여 파일 액세스를 제어할 수 있습니다.

클라이언트는 NFS와 SMB 프로토콜을 모두 사용하여 동일한 파일에 액세스할 수 있습니다.



== 중소기업

SMB는 Windows 시스템을 위한 전통적인 파일 접근 프로토콜입니다.  클라이언트는 SMB 2.0, SMB 2.1, SMB 3.0 및 SMB 3.1.1 프로토콜을 사용하여 ONTAP 볼륨의 파일에 액세스할 수 있습니다.  NFS와 마찬가지로 다양한 권한 스타일이 지원됩니다.



== S3

Cloud Volumes ONTAP 확장형 스토리지 옵션으로 S3를 지원합니다.  S3 프로토콜 지원을 통해 스토리지 VM(SVM)의 버킷에 포함된 개체에 대한 S3 클라이언트 액세스를 구성할 수 있습니다.

link:https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html#how-s3-multiprotocol-works["ONTAP 문서: S3 멀티프로토콜 작동 방식 알아보기"^] . link:https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["ONTAP 설명서: ONTAP 에서 S3 개체 스토리지 서비스를 구성하고 관리하는 방법을 알아보세요."^] .



== NVMe-TCP

ONTAP 버전 9.12.1부터 클라우드 공급자를 위해 NVMe-TCP가 지원됩니다.  NetApp 콘솔은 NVMe-TCP에 대한 관리 기능을 제공하지 않습니다.

ONTAP 통한 NVMe 구성에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html["ONTAP 설명서: NVMe를 위한 스토리지 VM 구성"^] .
