---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: 'freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet, bluexp license conversion for node based, license end of support (EOS) node-based, end of availability (EOA) of node-based' 
summary: Cloud Volumes ONTAP 에는 여러 가지 라이선싱 옵션이 제공됩니다. 각 옵션을 사용하면 필요에 맞는 구성을 선택할 수 있습니다. 
---
= Cloud Volumes ONTAP 라이선싱
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 에는 여러 가지 라이선싱 옵션이 제공됩니다. 각 옵션을 통해 귀하의 필요에 맞는 소비 모델을 선택할 수 있습니다.



== 라이센스 개요

신규 고객에게는 다음과 같은 라이선스 옵션이 제공됩니다.

용량 기반 라이선싱:: NetApp 계정에서 여러 Cloud Volumes ONTAP 시스템에 대한 비용을 프로비저닝된 용량에 따라 지불합니다.  추가 클라우드 데이터 서비스를 구매할 수 있는 기능이 포함되어 있습니다.  용량 기반 라이선스의 소비 모델에 대한 자세한 내용은 다음을 참조하세요.link:concept-licensing-charging.html["용량 기반 라이선스에 대해 자세히 알아보세요"] .
Keystone 구독:: 고가용성(HA) 쌍에 대한 원활한 하이브리드 클라우드 환경을 제공하는, 사용량에 따라 비용을 지불하는 구독 기반 서비스입니다.


다음 섹션에서는 각 옵션에 대한 자세한 내용을 설명합니다.


NOTE: 라이선스가 없으면 라이선스 기능을 사용할 수 없습니다.



== 용량 기반 라이선싱

용량 기반 라이선싱 패키지를 사용하면 TiB 용량당 Cloud Volumes ONTAP 비용을 지불할 수 있습니다. 라이선스는 NetApp 계정과 연결되며, 라이선스를 통해 충분한 용량을 사용할 수 있는 한 라이선스에 따라 여러 시스템에 요금을 청구할 수 있습니다.

예를 들어, 20TiB 라이선스 하나를 구매하고, Cloud Volumes ONTAP 시스템 4개를 배포한 다음, 각 시스템에 5TiB 볼륨을 할당하여 총 20TiB를 확보할 수 있습니다.  해당 계정에 배포된 각 Cloud Volumes ONTAP 시스템의 볼륨에서 용량을 사용할 수 있습니다.

용량 기반 라이선싱은 _패키지_ 형태로 제공됩니다. Cloud Volumes ONTAP 시스템을 배포하면 비즈니스 요구 사항에 따라 여러 가지 라이선스 패키지 중에서 선택할 수 있습니다.


NOTE: NetApp Console 에서 관리되는 제품과 서비스의 실제 사용량과 측정은 항상 GiB와 TiB로 계산되지만, GB/GiB와 TB/TiB라는 용어는 서로 바꿔 사용됩니다.  이는 클라우드 마켓플레이스 목록, 가격 견적, 목록 설명 및 기타 지원 문서에 반영되어 있습니다.



=== 패키지

다음과 같은 용량 기반 패키지는 Cloud Volumes ONTAP 에서 사용할 수 있습니다.  용량 기반 라이센스 패키지에 대한 자세한 내용은 다음을 참조하세요.link:concept-licensing-charging.html["용량 기반 라이선스에 대해 자세히 알아보세요"] .

다음 용량 기반 패키지가 포함된 지원되는 VM 유형 목록은 다음을 참조하세요.

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Azure에서 지원되는 구성"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloud에서 지원되는 구성"^]


endif::gcp[]



==== 프리미엄

NetApp 에서 모든 Cloud Volumes ONTAP 기능을 무료로 제공합니다(클라우드 공급자 요금은 여전히 ​​적용됩니다).  프리미엄 패키지에는 다음과 같은 특징이 있습니다.

* 라이센스나 계약이 필요하지 않습니다.
* NetApp 의 지원은 포함되지 않습니다.
* Cloud Volumes ONTAP 시스템당 프로비저닝 용량은 500GiB로 제한됩니다.
* NetApp 계정당 최대 10개의 Cloud Volumes ONTAP 시스템을 Freemium으로 모든 클라우드 공급자와 함께 사용할 수 있습니다.
* Cloud Volumes ONTAP 시스템의 프로비저닝된 용량이 500GiB를 초과하면 콘솔은 시스템을 Essentials 패키지로 전환합니다.
+
시스템이 Essentials 패키지로 변환되면link:concept-licensing-charging.html#minimum-charge["최소 충전"] 이에 적용됩니다.

+
Essentials 패키지로 전환된 Cloud Volumes ONTAP 시스템은 프로비저닝된 용량이 500GiB 미만으로 줄어들더라도 Freemium으로 다시 전환할 수 없습니다.  프로비저닝된 용량이 500GiB 미만인 다른 시스템은 Freemium을 유지합니다(Freemium 제공을 사용하여 배포된 경우).





==== 골자

다양한 구성으로 용량별로 요금을 지불할 수 있습니다.

* Cloud Volumes ONTAP 구성을 선택하세요.
+
** 단일 노드 또는 HA 시스템
** 재해 복구(DR)를 위한 파일 및 블록 스토리지 또는 보조 데이터


* 추가 비용으로 NetApp의 클라우드 데이터 서비스를 추가하세요




==== 전문적인

무제한 백업이 가능한 모든 유형의 Cloud Volumes ONTAP 구성에 대해 용량별로 요금을 지불하세요.

* 모든 Cloud Volumes ONTAP 구성에 대한 라이선싱을 제공합니다.
+
1차 및 2차 볼륨에 대해 동일한 요금으로 용량 요금을 청구하는 단일 노드 또는 HA

* NetApp Backup and Recovery 사용한 무제한 볼륨 백업이 포함되지만 Professional 패키지를 사용하는 Cloud Volumes ONTAP 시스템에만 해당됩니다.
+

NOTE: 백업 및 복구에는 사용량에 따른 요금(PAYGO) 구독이 필요하지만, 이 서비스 사용에는 요금이 부과되지 않습니다.  백업 및 복구에 대한 라이센싱 설정에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["백업 및 복구에 대한 라이선싱 설정"^] .

* 추가 비용으로 NetApp의 클라우드 데이터 서비스를 추가하세요




=== 용량 기반 라이선스의 가용성

Cloud Volumes ONTAP 시스템에 대한 PAYGO 및 BYOL 라이선스를 사용하려면 콘솔 에이전트가 작동 중이어야 합니다.

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#impact-on-cloud-volumes-ontap["콘솔 에이전트에 대해 알아보세요"^] .


NOTE: NetApp BYOL 라이선스 구매, 연장 및 갱신을 제한하고 있습니다. 자세한 내용은 다음을 참조하세요.  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAPP 에 대한 BYOL 라이선싱의 제한된 가용성"^] .



=== 시작하는 방법

용량 기반 라이선싱을 시작하는 방법을 알아보세요.

ifdef::aws[]

* link:task-set-up-licensing-aws.html["AWS에서 Cloud Volumes ONTAP 에 대한 라이선싱 설정"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Azure에서 Cloud Volumes ONTAP 에 대한 라이선싱 설정"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Google Cloud에서 Cloud Volumes ONTAP 에 대한 라이선싱 설정"]


endif::gcp[]



== Keystone 구독

선불 CapEx 또는 임대보다 OpEx 소비 모델을 선호하는 고객을 위해 원활한 하이브리드 클라우드 환경을 제공하는, 사용량에 따라 비용을 지불하는 구독 기반 서비스입니다.

요금은 Keystone 구독에서 하나 이상의 Cloud Volumes ONTAP HA 쌍에 대해 약속한 용량 크기에 따라 부과됩니다.

각 볼륨에 대해 제공된 용량은 집계되어 Keystone 구독에 약정된 용량과 주기적으로 비교되며, 초과분은 Keystone 구독에 버스트로 청구됩니다.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["NetApp Keystone 에 대해 자세히 알아보세요"^] .



=== 지원되는 구성

Keystone 구독은 HA 쌍으로 지원됩니다.  이 라이선싱 옵션은 현재 단일 노드 시스템에서는 지원되지 않습니다.



=== 용량 제한

용량 기반 라이선싱 모델에서 각 Cloud Volumes ONTAP 시스템은 개체 스토리지에 대한 계층화를 지원하며, 전체 계층화 용량은 클라우드 공급자의 버킷 한도까지 확장될 수 있습니다. 라이센스에는 용량 제한이 부과되지 않지만 다음을 따르십시오. https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool 모범 사례"^] 계층화를 구성하고 관리할 때 최적의 성능, 안정성 및 비용 효율성을 보장합니다.

각 클라우드 공급자의 용량 제한에 대한 자세한 내용은 해당 문서를 참조하세요.

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWS 문서"^]
* https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["관리 디스크에 대한 Azure 설명서"^]그리고 https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Blob 저장소에 대한 Azure 설명서"^]
* https://cloud.google.com/storage/docs/buckets["Google Cloud 문서"^]




=== 시작하는 방법

Keystone 구독을 시작하는 방법을 알아보세요.

ifdef::aws[]

* link:task-set-up-licensing-aws.html["AWS에서 Cloud Volumes ONTAP 에 대한 라이선싱 설정"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Azure에서 Cloud Volumes ONTAP 에 대한 라이선싱 설정"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Google Cloud에서 Cloud Volumes ONTAP 에 대한 라이선싱 설정"]


endif::gcp[]



== 노드 기반 라이선싱

노드 기반 라이선싱은 노드별로 Cloud Volumes ONTAP 대한 라이선스를 부여할 수 있는 이전 세대 라이선스 모델입니다.  이 라이선스 모델은 신규 고객에게는 제공되지 않습니다.  노드별 요금 청구는 위에 설명된 용량별 요금 청구 방식으로 대체되었습니다.

NetApp 노드 기반 라이선싱의 가용성 종료(EOA) 및 지원 종료(EOS)를 계획했습니다.  EOA 및 EOS 이후에는 노드 기반 라이선스를 용량 기반 라이선스로 전환해야 합니다.

자세한 내용은 다음을 참조하세요. https://mysupport.netapp.com/info/communications/CPC-00589.html["고객 공지: CPC-00589"^] .



=== 노드 기반 라이선스 제공 종료

2024년 11월 11일부터 노드 기반 라이선스의 제한된 제공이 종료되었습니다. 노드 기반 라이선싱에 대한 지원은 2024년 12월 31일에 종료됩니다.

EOA 날짜를 넘어서도 유효한 노드 기반 계약이 있는 경우, 계약이 만료될 때까지 라이선스를 계속 사용할 수 있습니다.  계약이 만료되면 용량 기반 라이선스 모델로 전환해야 합니다.  Cloud Volumes ONTAP 노드에 대한 장기 계약이 없는 경우 EOS 날짜 전에 전환을 계획하는 것이 중요합니다.

다음 표를 통해 각 라이선스 유형과 EOA가 라이선스 유형에 미치는 영향에 대해 자세히 알아보세요.

[cols="2*"]
|===
| 라이센스 유형 | EOA 이후의 영향 


 a| 
BYOL(Bring Your Own License)을 통해 구매한 유효한 노드 기반 라이선스
 a| 
라이센스는 만료일까지 유효합니다.  기존에 사용되지 않은 노드 기반 라이선스는 새로운 Cloud Volumes ONTAP 시스템을 배포하는 데 사용할 수 있습니다.



 a| 
BYOL을 통해 구매한 노드 기반 라이센스가 만료되었습니다.
 a| 
이 라이선스를 사용하여 새로운 Cloud Volumes ONTAP 시스템을 배포할 수 없습니다.  기존 시스템은 계속 작동할 수 있지만 EOS 날짜 이후에는 시스템에 대한 지원이나 업데이트를 받을 수 없습니다.



 a| 
PAYGO 구독이 포함된 유효한 노드 기반 라이센스
 a| 
EOS 날짜 이후에는 용량 기반 라이선스로 전환할 때까지 NetApp 지원을 받을 수 없습니다.

|===
.제외 사항
NetApp 특정 상황에서는 특별한 고려가 필요하다는 점을 인식하고 있으며, 노드 기반 라이선싱의 EOA 및 EOS는 다음과 같은 경우에는 적용되지 않습니다.

* 미국 공공 부문 고객
* 개인 모드 배포
* AWS에서 Cloud Volumes ONTAP 의 중국 지역 배포


이러한 특정 시나리오에서 NetApp 계약 의무와 운영적 요구 사항을 준수하면서 고유한 라이선스 요구 사항을 해결하기 위한 지원을 제공합니다.


NOTE: 이러한 시나리오에서도 새로운 노드 기반 라이선스와 라이선스 갱신은 승인일로부터 최대 1년 동안 유효합니다.



== 라이센스 변환

콘솔을 사용하면 라이선스 변환 도구를 통해 노드 기반 라이선스를 용량 기반으로 원활하게 변환할 수 있습니다.  노드 기반 라이센싱의 EOA에 대한 정보는 다음을 참조하세요.link:concept-licensing.html#end-of-availability-of-node-based-licenses["노드 기반 라이선스 제공 종료"] .

전환하기 전에 두 라이선스 모델의 차이점을 숙지하는 것이 좋습니다.  노드 기반 라이선싱에는 각 ONTAP 인스턴스에 대한 고정 용량이 포함되어 있어 유연성이 제한될 수 있습니다.  반면, 용량 기반 라이선싱은 여러 인스턴스에서 공유 스토리지 풀을 허용하여 유연성을 높이고 리소스 활용도를 최적화하며 작업 부하를 재분배할 때 발생할 수 있는 재정적 불이익 가능성을 줄입니다.  용량 기반 요금 청구는 변화하는 저장 요구 사항에 맞게 원활하게 조정됩니다.

이 변환을 수행하는 방법을 알아보려면 다음을 참조하세요.link:task-convert-node-capacity.html["Cloud Volumes ONTAP 노드 기반 라이선스를 용량 기반 라이선스로 변환"] .


NOTE: 용량 기반 라이선싱에서 노드 기반 라이선싱으로 시스템을 전환하는 것은 지원되지 않습니다.
