---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage, tiering 
summary: 'Cloud Volumes ONTAP 시스템에서 WORM(Write Once, Read Many) 스토리지를 활성화하여 지정된 보존 기간 동안 수정되지 않은 형태로 파일을 보존할 수 있습니다.  클라우드 WORM 스토리지는 SnapLock 기술을 기반으로 하며, 이는 WORM 파일이 파일 수준에서 보호된다는 것을 의미합니다.' 
---
= Cloud Volumes ONTAP 의 WORM 스토리지에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 시스템에서 WORM(Write Once, Read Many) 스토리지를 활성화하여 지정된 보존 기간 동안 수정되지 않은 형태로 파일을 보존할 수 있습니다.  클라우드 WORM 스토리지는 SnapLock 기술을 기반으로 하며, 이는 WORM 파일이 파일 수준에서 보호된다는 것을 의미합니다.

WORM 기능은 추가 비용 없이 BYOL(Bring Your Own License) 및 마켓플레이스 구독을 통해 라이선스를 구매할 때 사용할 수 있습니다.  현재 라이선스에 WORM을 추가하려면 NetApp 영업 담당자에게 문의하세요.



== WORM 스토리지 작동 방식

파일이 WORM 저장소에 커밋되면 보존 기간이 만료된 후에도 해당 파일을 수정할 수 없습니다.  변조 방지 시계는 WORM 파일의 보존 기간이 경과한 시점을 판별합니다.

보관 기간이 경과한 후에는 더 이상 필요하지 않은 파일을 삭제해야 합니다.



== WORM 스토리지 활성화

WORM 스토리지를 활성화하는 방법은 사용 중인 Cloud Volumes ONTAP 버전에 따라 달라집니다.



=== 버전 9.10.1 이상

Cloud Volumes ONTAP 9.10.1부터 볼륨 수준에서 WORM을 활성화하거나 비활성화하는 옵션이 제공됩니다.

Cloud Volumes ONTAP 시스템을 추가하면 WORM 스토리지를 활성화하거나 비활성화하라는 메시지가 표시됩니다.

* 시스템을 추가할 때 WORM 스토리지를 활성화하면 NetApp Console 에서 생성하는 모든 볼륨에 WORM이 활성화됩니다.  하지만 ONTAP 시스템 관리자나 ONTAP CLI를 사용하면 WORM이 비활성화된 볼륨을 생성할 수 있습니다.
* 시스템을 추가할 때 WORM 저장소를 비활성화하면 콘솔, ONTAP 시스템 관리자 또는 ONTAP CLI에서 생성하는 모든 볼륨에서 WORM이 비활성화됩니다.




=== 버전 9.10.0 및 이전 버전

새로운 시스템을 추가할 때 Cloud Volumes ONTAP 시스템에서 WORM 스토리지를 활성화할 수 있습니다.  콘솔에서 생성하는 모든 볼륨에는 WORM이 활성화되어 있습니다.  개별 볼륨에서 WORM 저장소를 비활성화할 수 없습니다.



== WORM에 파일 커밋

NFS 또는 CIFS를 통해 WORM에 파일을 커밋하려면 애플리케이션을 사용하거나 ONTAP CLI를 사용하여 자동으로 파일을 WORM에 커밋할 수 있습니다.  또한 WORM 추가 가능 파일을 사용하여 로그 정보와 같이 증분적으로 기록되는 데이터를 보관할 수 있습니다.

Cloud Volumes ONTAP 시스템에서 WORM 스토리지를 활성화한 후에는 WORM 스토리지의 모든 관리에 ONTAP CLI를 사용해야 합니다.  지침은 다음을 참조하세요. http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["SnapLock 에 대한 ONTAP 문서"^] .



== Cloud Volumes ONTAP 시스템에서 WORM 활성화

콘솔에서 Cloud Volumes ONTAP 시스템을 생성할 때 WORM 스토리지를 활성화할 수 있습니다.  생성 중에 WORM이 활성화되지 않은 경우에도 시스템에서 WORM을 활성화할 수 있습니다.  WORM을 활성화한 후에는 비활성화할 수 없습니다.

.이 작업에 관하여
* WORM은 ONTAP 9.10.1 이상에서 지원됩니다.
* 백업 기능이 있는 WORM은 ONTAP 9.11.1 이상에서 지원됩니다.


.단계
. *시스템* 페이지에서 WORM을 활성화하려는 시스템의 이름을 두 번 클릭합니다.
. 개요 탭에서 기능 패널을 클릭한 다음 *WORM* 옆에 있는 연필 아이콘을 클릭합니다.
+
시스템에서 WORM이 이미 활성화된 경우 연필 아이콘은 비활성화됩니다.

. *WORM* 페이지에서 클러스터 규정 준수 시계의 보존 기간을 설정합니다.
+
자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/snaplock/initialize-complianceclock-task.html["ONTAP 설명서: 규정 준수 시계 초기화"^] .

. *설정*을 클릭하세요.


.당신이 완료한 후
*WORM*의 상태는 기능 패널에서 확인할 수 있습니다.  WORM이 활성화되면 SnapLock 라이선스가 클러스터에 자동으로 설치됩니다.  ONTAP System Manager에서 SnapLock 라이선스를 볼 수 있습니다.



== WORM 파일 삭제

권한 있는 삭제 기능을 사용하여 보존 기간 동안 WORM 파일을 삭제할 수 있습니다.

지침은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html["ONTAP 문서"^] .



== WORM 및 데이터 계층화

새로운 Cloud Volumes ONTAP 9.8 시스템 이상을 만들면 데이터 계층화와 WORM 스토리지를 함께 활성화할 수 있습니다.  WORM 스토리지를 사용하여 데이터 계층화를 활성화하면 클라우드의 개체 저장소에 데이터를 계층화할 수 있습니다.

데이터 계층화와 WORM 스토리지를 모두 활성화하는 데 필요한 다음 사항을 이해해야 합니다.

* 개체 스토리지에 계층화된 데이터에는 ONTAP WORM 기능이 포함되지 않습니다.  엔드투엔드 WORM 기능을 보장하려면 버킷 권한을 올바르게 설정해야 합니다.
* 개체 스토리지에 계층화된 데이터에는 WORM 기능이 없으므로, 기술적으로 버킷과 컨테이너에 대한 전체 액세스 권한이 있는 사람은 누구나 ONTAP 에 의해 계층화된 개체를 삭제할 수 있습니다.
* WORM 및 계층화를 활성화한 후에는 Cloud Volumes ONTAP 9.8로 되돌리거나 다운그레이드하는 것이 차단됩니다.




== 제한 사항

* Cloud Volumes ONTAP 의 WORM 스토리지는 "신뢰할 수 있는 스토리지 관리자" 모델에 따라 작동합니다.  WORM 파일은 변경이나 수정으로부터 보호되지만, 볼륨에 만료되지 않은 WORM 데이터가 포함되어 있더라도 클러스터 관리자가 볼륨을 삭제할 수 있습니다.
* 신뢰할 수 있는 스토리지 관리자 모델 외에도 Cloud Volumes ONTAP 의 WORM 스토리지는 암묵적으로 "신뢰할 수 있는 클라우드 관리자" 모델에 따라 작동합니다.  클라우드 관리자는 클라우드 제공자로부터 직접 클라우드 스토리지를 제거하거나 편집하여 만료일 전에 WORM 데이터를 삭제할 수 있습니다.


.관련 링크
* link:reference-worm-snaplock.html["WORM 스토리지를 위한 변조 방지 스냅샷 복사본 생성"]

