---
settings:
  name: Cloud Volumes ONTAP
  harmony_integration: maestro
  release_notes_autogen:
    release_notes_repo: console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: 클라우드 제공업체
    default: 모든 클라우드 제공업체
    options:
    - name: 아마존 웹 서비스
      alias: AWS
      id: aws
    - name: 구글 클라우드
      alias: 구글 클라우드
      id: gcp
    - name: 마이크로소프트 애저
      alias: 하늘빛
      id: azure
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: Cloud Volumes ONTAP 문서
    url: "/index.html"
  - title: 릴리스 노트
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
    - title: 알려진 제한 사항
      url: "/reference-limitations.html"
    - title: Cloud Volumes ONTAP 릴리스 노트
      url: "/whats-new-ontap.html"
  - title: 시작하기
    entries:
    - title: Cloud Volumes ONTAP 에 대해 알아보세요
      url: "/concept-overview-cvo.html"
    - title: 새로운 배포에 지원되는 ONTAP 버전
      url: "/reference-versions.html"
    - title: Amazon Web Services에서 시작하세요
      flavor: aws
      entries:
      - title: 빠른 시작
        url: "/task-getting-started-aws.html"
      - title: 구성을 계획하세요
        url: "/task-planning-your-config.html"
      - title: 네트워킹을 설정하세요
        entries:
        - title: AWS 네트워킹 설정
          url: "/reference-networking-aws.html"
        - title: AWS 전송 게이트웨이 설정
          url: "/task-setting-up-transit-gateway.html"
        - title: 공유 서브넷에 HA 쌍 배포
          url: "/task-deploy-aws-shared-vpc.html"
        - title: AWS 배치 그룹 생성을 위해 Cloud Volumes ONTAP 구성
          url: "/task-configure-placement-group-failure-aws.html"
        - title: AWS 보안 그룹 규칙
          url: "/reference-security-groups.html"
      - title: AWS KMS 설정
        url: "/task-setting-up-kms.html"
      - title: IAM 역할 설정
        url: "/task-set-up-iam-roles.html"
      - title: 라이센스 설정
        url: "/task-set-up-licensing-aws.html"
      - title: AWS에서 Cloud Volumes ONTAP 에 대한 빠른 배포 방법 사용
        url: "/task-quick-deploy-aws.html"
      - title: AWS에서 Cloud Volumes ONTAP 에 대한 고급 배포 방법 사용
        url: "/task-deploying-otc-aws.html"
      - title: AWS Secret 지역에 Cloud Volumes ONTAP 배포
        url: "/task-getting-started-aws-c2s.html"
    - title: Microsoft Azure에서 시작하기
      flavor: azure
      entries:
      - title: Azure에서 Cloud Volumes ONTAP 배포 옵션에 대해 알아보세요.
        url: "/concept-azure-mktplace-direct.html"
      - title: NetApp Console 에서 시작하기
        entries:
        - title: 빠른 시작
          url: "/task-getting-started-azure.html"
        - title: 구성을 계획하세요
          url: "/task-planning-your-config-azure.html"
        - title: 네트워킹을 설정하세요
          url: "/reference-networking-azure.html"
        - title: 키를 사용하여 암호화를 설정하세요
          url: "/task-set-up-azure-encryption.html"
        - title: 라이센스 설정
          url: "/task-set-up-licensing-azure.html"
        - title: 고가용성 모드 활성화
          url: "/task-azure-high-availability-mode.html"
        - title: 단일 가용성 영역에 대해 VMOrchestratorZonalMultiFD 활성화
          url: "/task-saz-feature.html"
        - title: Azure에서 Cloud Volumes ONTAP 실행
          url: "/task-deploying-otc-azure.html"
        - title: Azure 플랫폼 이미지 확인
          entries:
          - title: 개요
            url: "/concept-azure-image-verification.html"
          - title: Azure 이미지 파일 다운로드
            url: "/task-azure-download-digest-file.html"
          - title: Azure 이미지 파일 내보내기
            url: "/task-azure-image-export.html"
          - title: 파일 서명 확인
            entries:
            - title: 파일 서명 확인에 대해 알아보세요
              url: "/concept-azure-file-sig-verify.html"
            - title: Linux에서 파일 서명 확인
              url: "/task-file-verification-linux.html"
            - title: macOS에서 파일 서명 확인
              url: "/task-file-verification-mac.html"
      - title: 마켓플레이스에서 시작하세요
        url: "/task-deploy-cvo-azure-mktplc.html"
    - title: Google Cloud에서 시작하기
      flavor: gcp
      entries:
      - title: 빠른 시작
        url: "/task-getting-started-gcp.html"
      - title: 구성을 계획하세요
        url: "/task-planning-your-config-gcp.html"
      - title: 네트워킹을 설정하세요
        url: "/reference-networking-gcp.html"
      - title: VPC 서비스 제어 계획
        url: "/reference-vpc-service-controls-gcp.html"
      - title: 서비스 계정 생성
        url: "/task-creating-gcp-service-account.html"
      - title: 고객 관리 암호화 키 사용
        url: "/task-setting-up-gcp-encryption.html"
      - title: 라이센스 설정
        url: "/task-set-up-licensing-google.html"
      - title: Google Cloud에서 Cloud Volumes ONTAP 실행
        url: "/task-deploying-gcp.html"
      - title: Google Cloud Platform 이미지 검증
        entries:
        - title: 개요
          url: "/concept-gcp-image-verification.html"
        - title: GCP에서 이미지를 Raw 형식으로 변환
          url: "/task-gcp-convert-image-raw.html"
        - title: 이미지 서명 검증
          entries:
          - title: GCP 서명 이미지 확인
            url: "/concept-gcp-verify-signed-image.html"
          - title: OpenSSL을 사용하여 콘텐츠 확인
            url: "/task-verify-openssl-gcp.html"
  - title: Cloud Volumes ONTAP 사용
    entries:
    - title: 라이선스 관리
      entries:
      - title: 용량 기반 라이선스 관리
        url: "/task-manage-capacity-licenses.html"
      - title: Keystone 구독 관리
        url: "/task-manage-keystone.html"
      - title: 노드 기반 라이선스 관리
        url: "/task-manage-node-licenses.html"
    - title: 볼륨 및 LUN 관리
      entries:
      - title: 볼륨 생성
        url: "/task-create-volumes.html"
      - title: 기존 볼륨 관리
        url: "/task-manage-volumes.html"
      - title: 비활성 데이터를 개체 스토리지로 계층화
        url: "/task-tiering.html"
      - title: LUN을 호스트에 연결
        url: "/task-connect-lun.html"
      - title: FlexCache 로 데이터 액세스 가속화
        url: "/task-accelerate-data-access.html"
    - title: 집계 관리
      entries:
      - title: 집계 생성
        url: "/task-create-aggregates.html"
      - title: 기존 집계 관리
        url: "/task-manage-aggregates.html"
      - title: 용량 설정 관리
        url: "/task-manage-capacity-settings.html"
    - title: 스토리지 VM 관리
      entries:
      - title: 스토리지 VM 작업
        url: "/task-managing-svms.html"
      - title: AWS에서 스토리지 VM 관리
        flavor: aws
        url: "/task-managing-svms-aws.html"
      - title: Azure에서 스토리지 VM 관리
        flavor: azure
        url: "/task-managing-svms-azure.html"
      - title: Google Cloud에서 스토리지 VM 관리
        flavor: gcp
        url: "/task-managing-svms-gcp.html"
      - title: SVM 재해 복구 설정
        url: "/task-manage-svm-dr.html"
    - title: 보안 및 데이터 암호화
      entries:
      - title: NetApp 암호화로 볼륨 암호화
        url: "/task-encrypting-volumes.html"
      - title: AWS Key Management Service로 키 관리
        flavor: aws
        url: "/task-aws-key-management.html"
      - title: Azure Key Vault를 사용하여 키 관리
        flavor: azure
        url: "/task-azure-key-vault.html"
      - title: Google Cloud KMS로 키 관리
        flavor: gcp
        url: "/task-google-key-manager.html"
      - title: 랜섬웨어 보호 강화
        url: "/task-protecting-ransomware.html"
      - title: WORM 스토리지를 위한 변조 방지 스냅샷 복사본 생성
        url: "/reference-worm-snaplock.html"
    - title: 시스템 관리
      entries:
      - title: Cloud Volumes ONTAP 업그레이드
        url: "/task-updating-ontap-cloud.html"
      - title: 선불 시스템 등록
        url: "/task-registering.html"
      - title: 노드 기반 라이센스 변환
        url: "/task-convert-node-capacity.html"
      - title: 시스템 중지 및 시작
        url: "/task-managing-state.html"
      - title: 시스템 시간 동기화
        url: "/task-sync-time.html"
      - title: 시스템 쓰기 속도 수정
        url: "/task-modify-write-speed.html"
      - title: 시스템 비밀번호 변경
        url: "/task-change-password.html"
      - title: 시스템 추가, 제거 또는 삭제
        entries:
        - title: 기존 시스템 추가
          url: "/task-adding-systems.html"
        - title: 시스템 제거
          url: "/task-removing.html"
        - title: 시스템 삭제
          url: "/task-deleting-system.html"
      - title: AWS 관리
        flavor: aws
        entries:
        - title: AWS에서 EC2 인스턴스 작업
          url: "/task-change-ec2-instance.html"
        - title: HA 쌍에 대한 경로 테이블 변경
          url: "/task-change-route-tables.html"
        - title: 배치 그룹 생성 구성
          url: task-configure-placement-group-failure-aws.html
      - title: Azure 관리
        flavor: azure
        entries:
        - title: Azure VM 유형 변경
          url: "/task-change-azure-vm.html"
        - title: CIFS 잠금 재정의
          url: "/task-overriding-cifs-locks.html"
        - title: Azure Private Link 또는 서비스 엔드포인트 사용
          url: "/task-enabling-private-link.html"
        - title: 리소스 그룹 이동
          url: "/task-moving-resource-groups-azure.html"
        - title: Azure에서 SnapMirror 트래픽 분리
          url: "/task-segregate-snapmirror-azure.html"
      - title: Google Cloud 관리
        flavor: gcp
        entries:
        - title: 기계 유형 변경
          url: "/task-change-gcp-machine.html"
      - title: 시스템 관리자의 관리
        url: "/task-administer-advanced-view.html"
      - title: CLI에서의 관리
        url: "/task-connecting-to-otc.html"
    - title: 시스템 상태 및 이벤트
      entries:
      - title: AutoSupport 설정 확인
        url: "/task-verify-autosupport.html"
      - title: EMS 구성
        url: "/task-configure-ems.html"
  - title: 개념
    entries:
    - title: 라이센스
      entries:
      - title: Cloud Volumes ONTAP 라이선싱
        url: "/concept-licensing.html"
      - title: 용량 기반 라이선스에 대해 자세히 알아보세요
        url: "/concept-licensing-charging.html"
    - title: 스토리지
      entries:
      - title: 클라이언트 프로토콜
        url: "/concept-client-protocols.html"
      - title: 디스크 및 집계
        url: "/concept-storage.html"
      - title: AWS의 탄력적 볼륨
        flavor: aws
        url: "/concept-aws-elastic-volumes.html"
      - title: 데이터 계층화
        url: "/concept-data-tiering.html"
      - title: 스토리지 관리
        url: "/concept-storage-management.html"
      - title: 쓰기 속도
        url: "/concept-write-speed.html"
      - title: Flash Cache
        url: "/concept-flash-cache.html"
      - title: WORM 스토리지
        url: "/concept-worm.html"
    - title: 고가용성 쌍
      entries:
      - title: AWS의 HA 쌍
        flavor: aws
        url: "/concept-ha.html"
      - title: Azure의 HA 쌍
        flavor: azure
        url: "/concept-ha-azure.html"
      - title: GCP의 HA 쌍
        flavor: gcp
        url: "/concept-ha-google-cloud.html"
      - title: 저장소 인수 중 작업
        url: "/concept-degraded-ha-pair.html"
    - title: 보안
      url: "/concept-security.html"
    - title: 성능
      url: "/concept-performance.html"
    - title: 노드 기반 BYOL 관리
      url: "/concept-license-management.html"
    - title: AutoSupport 및 Digital Advisor
      url: "/concept-active-iq.html"
    - title: 기본 구성
      url: "/reference-default-configs.html"
  - title: 지식과 지원
    entries:
    - title: 지원 등록
      url: "/task-support-registration.html"
    - title: 도움을 받으세요
      url: "/task-get-help.html"
  - title: 법적 고지 사항
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
