---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, flexgroup, ontap s3, s3 configuration, svm dr, svm disaster recovery, disaster recovery, storage vm dr, BlueXP, Console, cloud manager 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요. 
---
= 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요.

이러한 제한 사항은 NetApp Console 의 Cloud Volumes ONTAP 관리에만 적용됩니다.  Cloud Volumes ONTAP 소프트웨어 자체의 제한 사항을 보려면 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html["Cloud Volumes ONTAP 릴리스 노트로 이동"^] .



== 콘솔은 FlexGroup 볼륨 생성을 지원하지 않습니다.

Cloud Volumes ONTAP FlexGroup 볼륨을 지원하지만 콘솔은 현재 FlexGroup 볼륨 생성을 지원하지 않습니다.  ONTAP System Manager 또는 ONTAP CLI에서 FlexGroup 볼륨을 생성하는 경우 콘솔에서 용량 관리 모드를 설정해야 합니다. `Manual` . `Automatic` FlexGroup 볼륨에서는 모드가 제대로 작동하지 않을 수 있습니다.


NOTE: 콘솔에서 FlexGroup 볼륨을 생성하는 기능은 향후 릴리스에서 제공될 예정입니다.



== 콘솔은 Cloud Volumes ONTAP 사용하는 S3를 지원하지 않습니다.

Cloud Volumes ONTAP는 스케일아웃 스토리지 옵션으로 S3를 지원하지만 Console에서는 이 기능에 대한 관리 기능을 제공하지 않습니다. 명령줄을 사용하는 것이 Cloud Volumes ONTAP에서 S3 클라이언트 액세스를 구성하는 모범 사례입니다. 자세한 내용은 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["ONTAP S3 구성 파워 가이드"^]을 참조하십시오.

link:concept-client-protocols.html["Cloud Volumes ONTAP의 ONTAP S3 및 기타 클라이언트 프로토콜 지원에 대해 자세히 알아보십시오"].



== 콘솔은 스토리지 VM에 대한 재해 복구를 지원하지 않습니다.

콘솔은 스토리지 VM(SVM) 재해 복구에 대한 설정이나 오케스트레이션 지원을 제공하지 않습니다.  ONTAP 시스템 관리자나 ONTAP CLI를 사용해야 합니다.

link:task-manage-svm-dr.html["SVM 재해 복구에 대해 자세히 알아보세요"] .
