---
sidebar: sidebar 
permalink: reference-vpc-service-controls-gcp.html 
keywords: vpc, service controls, vpc-sc, google, psc, private service connect 
summary: VPC 서비스 제어를 사용하여 Google 환경을 잠그기로 선택하는 경우 NetApp Console 과 Cloud Volumes ONTAP Google API와 상호 작용하는 방식과 Cloud Volumes ONTAP 배포하기 위해 서비스 매개변수를 구성하는 방법을 이해해야 합니다. 
---
= Google Cloud에 Cloud Volumes ONTAP 배포하기 위한 VPC 서비스 제어 설정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VPC 서비스 제어를 사용하여 Google Cloud 환경을 잠그기로 선택하는 경우 NetApp Console 과 Cloud Volumes ONTAP Google Cloud API와 상호 작용하는 방식과 Console과 Cloud Volumes ONTAP 배포하기 위해 서비스 경계를 ​​구성하는 방법을 이해해야 합니다.

VPC 서비스 제어를 사용하면 신뢰할 수 있는 경계 외부에서 Google 관리 서비스에 대한 액세스를 제어하고, 신뢰할 수 없는 위치에서의 데이터 액세스를 차단하고, 승인되지 않은 데이터 전송 위험을 완화할 수 있습니다. https://cloud.google.com/vpc-service-controls/docs["Google Cloud VPC 서비스 제어에 대해 자세히 알아보세요"^] .



== NetApp 서비스가 VPC 서비스 제어와 통신하는 방법

콘솔은 Google Cloud API와 직접 통신합니다.  이는 Google Cloud 외부의 외부 IP 주소(예: api.services.cloud.netapp.com)에서 트리거되거나, Google Cloud 내에서 Console 에이전트에 할당된 내부 주소에서 트리거됩니다.

콘솔 에이전트의 배포 스타일에 따라 서비스 경계에 대한 특정 예외를 만들어야 할 수도 있습니다.



== 이미지

Cloud Volumes ONTAP 과 콘솔은 모두 NetApp 에서 관리하는 GCP 내 프로젝트의 이미지를 사용합니다.  조직 내에서 호스팅되지 않은 이미지 사용을 차단하는 정책이 있는 경우, 이는 콘솔 에이전트와 Cloud Volumes ONTAP 의 배포에 영향을 미칠 수 있습니다.

수동 설치 방법을 사용하여 콘솔 에이전트를 수동으로 배포할 수 있지만 Cloud Volumes ONTAP 도 NetApp 프로젝트에서 이미지를 가져와야 합니다.  콘솔 에이전트와 Cloud Volumes ONTAP 배포하려면 허용 목록을 제공해야 합니다.



=== 콘솔 에이전트 배포

콘솔 에이전트를 배포하는 사용자는 프로젝트 ID _netapp-cloudmanager_와 프로젝트 번호 _14190056516_에 호스팅된 이미지를 참조할 수 있어야 합니다.



=== Cloud Volumes ONTAP 배포

* 콘솔 서비스 계정은 서비스 프로젝트의 프로젝트 ID _netapp-cloudmanager_와 프로젝트 번호 _14190056516_에 호스팅된 이미지를 참조해야 합니다.
* 기본 Google API 서비스 에이전트의 서비스 계정은 서비스 프로젝트의 프로젝트 ID _netapp-cloudmanager_와 프로젝트 번호 _14190056516_에 호스팅된 이미지를 참조해야 합니다.


VPC 서비스 제어를 사용하여 이러한 이미지를 가져오는 데 필요한 규칙의 예는 아래와 같습니다.



== VPC 서비스 제어 경계 정책

정책은 VPC 서비스 제어 규칙 세트에 대한 예외를 허용합니다.  정책에 대한 자세한 내용은 다음을 방문하세요. https://cloud.google.com/vpc-service-controls/docs/ingress-egress-rules#policy-model["GCP VPC 서비스 제어 정책 문서"^] .

콘솔에 필요한 정책을 설정하려면 조직 내의 VPC 서비스 제어 경계로 이동하여 다음 정책을 추가하세요.  필드는 VPC 서비스 제어 정책 페이지에 제공된 옵션과 일치해야 합니다.  또한 *모든* 규칙이 필수이며 규칙 세트에서는 *OR* 매개변수를 사용해야 합니다.



=== Ingress 규칙

....
From:
	Identities:
		[User Email Address]
	Source > All sources allowed
To:
	Projects =
		[Service Project]
	Services =
		Service name: iam.googleapis.com
		  Service methods: All actions
		Service name: compute.googleapis.com
		  Service methods:All actions
....
또는

....
From:
	Identities:
		[User Email Address]
	Source > All sources allowed
To:
	Projects =
		[Host Project]
	Services =
		Service name: compute.googleapis.com
		  Service methods: All actions
....
또는

....
From:
	Identities:
		[Service Project Number]@cloudservices.gserviceaccount.com
	Source > All sources allowed
To:
	Projects =
		[Service Project]
		[Host Project]
	Services =
		Service name: compute.googleapis.com
		Service methods: All actions
....


=== 탈출 규칙

....
From:
	Identities:
		[Service Project Number]@cloudservices.gserviceaccount.com
To:
	Projects =
		14190056516
	Service =
		Service name: compute.googleapis.com
		Service methods: All actions
....

TIP: 위에 설명된 프로젝트 번호는 NetApp 에서 콘솔 에이전트와 Cloud Volumes ONTAP 의 이미지를 저장하는 데 사용되는 프로젝트 _netapp-cloudmanager_입니다.
