---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache; limitations in HA deployment in MAZ, SAZ, multiple availability xone, single availability zone Azure CVO, PSSDv2, premium SSD v2 limitation in CVO, flash cache limitation in CVO 
summary: 이러한 알려진 제한 사항은 Microsoft Azure의 Cloud Volumes ONTAP에만 해당됩니다. 
---
= Azure에서 Cloud Volumes ONTAP의 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음은 Microsoft Azure의 Cloud Volumes ONTAP에 특정한 알려진 제한 사항입니다. link:reference-limitations.html["모든 클라우드 공급자의 Cloud Volumes ONTAP에 대한 제한 사항"]도 검토해 보시기 바랍니다.



[[limitations-with-using-azure-vm-extensions]]
== Azure VM 확장 사용 시 제한 사항

Cloud Volumes ONTAP는 NetApp Console의 관리 작업에 영향을 미치기 때문에 Azure 가상 머신(VM) 확장을 지원하지 않습니다. 배포 중에 Console은 VM에 확장이 설치되는 것을 방지합니다. 기존 Cloud Volumes ONTAP VM에 이미 확장이 설치된 경우 Microsoft Azure Support에 문의하여 제거하십시오. 자세한 내용은 기술 자료(KB) 문서를 참조하십시오. https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["Azure VM 관리 확장 기능을 Cloud Volumes ONTAP에 설치할 수 있습니까?"^]

2025년 7월 14일부터 NetApp은 Cloud Volumes ONTAP VM에서 VM 확장이 감지되면 이메일을 보내고 Console을 통해 알림을 보낼 예정입니다.



[[premium-ssd-v2-disks-limitations-for-ha-configurations]]
== HA 구성에 대한 Premium SSD v2 디스크 제한 사항

Premium SSD v2 Managed Disks는 Azure의 고가용성(HA) 배포에 대해 다음과 같은 제한 사항이 있습니다.

* 비영역 지역의 HA 배포에서는 지원되지 않습니다.
* 여러 가용 영역에 걸친 HA 배포에서는 지원되지 않습니다.
* 단일 가용성 영역 내에 배포된 HA 구성에서만 지원됩니다.


Cloud Volumes ONTAP HA 구성에서 Premium SSD v2 Managed Disks를 사용하려면 다음 요구 사항을 충족해야 합니다.

* Cloud Volumes ONTAP 버전은 9.15.1 이상입니다.
* HA 배포는 Azure 단일 가용성 영역에 있습니다.
* 선택된 지역 및 영역은 Premium SSD v2 관리형 디스크를 지원합니다. 지원되는 지역에 대한 자세한 내용은 https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Microsoft Azure 웹사이트: 지역별 사용 가능한 제품"^]를 참조하십시오.


자세한 내용은 https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#support-for-premium-ssd-v2-managed-disks-in-azure["Azure에서 Premium SSD v2 Managed Disks 지원"^]을 참조하십시오.



[[limitations-with-ha-deployments-in-single-availability-zones]]
== 단일 가용성 영역의 HA 배포 제한 사항

Cloud Volumes ONTAP 9.15.1부터 Azure의 단일 가용 영역(AZ)에 고가용성(HA) 모드로 가상 머신(VM) 인스턴스를 배포할 수 있습니다. 이 기능을 지원하는 기준에 대한 자세한 내용은 https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-in-azure["Azure의 단일 가용성 영역에 HA 쌍 배포"^]를 참조하세요.

Cloud Volumes ONTAP 버전이 9.15.1 이전이거나 이러한 조건 중 하나라도 충족되지 않으면 가용성 세트를 활용하는 이전 배포 모델이 적용됩니다. 이는 HA 구성에만 적용됩니다.



[[flash-cache-limitations]]
== Flash Cache 제한 사항

Cloud Volumes ONTAP는 일부 VM 유형에서 로컬 NVMe 스토리지를 _Flash Cache_로 사용합니다. 다음 제한 사항에 유의하십시오.

* 재부팅 후 캐시 재가열은 지원되지 않습니다.




[[limitations-with-ha-deployments]]
== HA 배포의 제한 사항

일부 지역에서는 HA 쌍이 지원되지 않습니다.

https://bluexp.netapp.com/cloud-volumes-global-regions["지원되는 Azure 지역 목록 보기"^].
