---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP는 안정적인 운영을 위해 AWS에서 스토리지 구성 제한을 두고 있습니다. 최상의 성능을 위해서는 시스템을 최대값으로 구성하지 마십시오. 
---
= AWS의 Cloud Volumes ONTAP 대한 스토리지 한도
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP에는 안정적인 운영을 위한 스토리지 구성 제한이 있습니다. 최상의 성능을 위해서는 시스템을 최대값으로 구성하지 마십시오.



[[maximum-system-capacity-by-license]]
== 라이센스별 최대 시스템 용량

최대 시스템 용량에는 디스크 기반 스토리지와 데이터 계층화에 사용되는 오브젝트 스토리지가 포함됩니다.

NetApp은 시스템 용량 제한 초과를 지원하지 않습니다. 라이센스 용량 제한에 도달하면 NetApp Console에 조치 필요 메시지가 표시되고 더 이상 디스크를 추가할 수 없습니다.

일부 구성에서는 디스크 제한으로 인해 디스크만으로는 용량 제한에 도달할 수 없습니다. 이러한 경우에는 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 개체 스토리지로 계층화"^]를 통해 용량 제한에 도달할 수 있습니다. 자세한 내용은 아래의 용량 및 디스크 제한을 참조하십시오.

[[cap-license-aws]]
.용량 기반 라이센스의 용량 제한
용량 기반 라이선스를 사용하는 각 Cloud Volumes ONTAP 시스템은 객체 스토리지로의 계층화를 지원합니다. 계층화된 총 용량은 클라우드 공급자의 버킷 제한까지 확장할 수 있습니다. 라이선스는 용량 제한을 부과하지 않지만 계층화를 구성하고 관리할 때 최적의 성능, 안정성 및 비용 효율성을 보장하기 위해 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool 모범 사례"^]를 따라야 합니다. 자세한 내용은 https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWS 문서"^]를 참조하십시오.

다른 라이센스 유형에 대한 용량 제한::


[cols="25,75"]
|===
| 라이센스 | 최대 시스템 용량(디스크 + 오브젝트 스토리지) 


| 프리미엄 | 500기가바이트 


| PAYGO Explore | 2TiB(Explore에서는 데이터 계층화가 지원되지 않음) 


| PAYGO Standard | 10 TiB 


| PAYGO Premium | 368 TiB 


| 노드 기반 라이센스 | 2 PiB(여러 라이센스 필요) 
|===
.HA의 경우 라이센스 용량 제한이 노드당 적용됩니까, 아니면 전체 HA 쌍에 적용됩니까?
용량 제한은 전체 HA 쌍에 대한 것입니다. 노드별 제한이 아닙니다. 예를 들어, Premium 라이센스는 두 노드를 합쳐 최대 368TiB까지 사용할 수 있습니다.

.AWS의 HA 시스템에서 미러링된 데이터는 용량 제한에 포함되나요?
아니요, 그렇지 않습니다. AWS HA 쌍의 데이터는 노드 간에 동기적으로 미러링되므로 장애 발생 시에도 데이터를 사용할 수 있습니다. 예를 들어 노드 A에서 8TiB 디스크를 구매하면 NetApp Console에서 노드 B에 미러링된 데이터에 사용되는 8TiB 디스크도 할당합니다. 16TiB의 용량이 프로비저닝되지만 라이센스 제한에는 8TiB만 포함됩니다.



[[aggregate-limits]]
== 애그리게이트 제한

Cloud Volumes ONTAP는 EBS 볼륨을 디스크로 사용하고 이를 _애그리게이트_로 그룹화합니다. 애그리게이트는 볼륨에 스토리지를 제공합니다.

[cols="2*"]
|===
| 매개변수 | 제한 


| 최대 애그리게이트 수 | 단일 노드: 디스크 제한과 동일 HA 쌍: 노드당 18개 ^1^ 


| 최대 애그리게이트 크기 ^2^  a| 
* 96TiB의 raw 용량
* Elastic Volumes를 사용한 128TiB의 raw 용량 ^3^




| 애그리게이트당 디스크 ^4^  a| 
* 1-6
* Elastic Volumes가 있는 4 또는 8 ^3^




| 애그리게이트당 최대 RAID 그룹 수 | 2 
|===
참고:

. HA 쌍의 두 노드 모두에 18개의 애그리게이트를 생성할 수 없습니다. 데이터 디스크 제한을 초과하기 때문입니다.
. 최대 애그리게이트 크기는 디스크에 따라 달라지며 데이터 계층화에 사용하는 오브젝트 스토리지는 포함되지 않습니다.
. Amazon EBS Elastic Volumes 기능을 지원하는 구성의 경우, 하나의 애그리게이트에 최대 8개의 디스크를 포함할 수 있으며, 이를 통해 최대 128TiB의 용량을 확보할 수 있습니다. 기본적으로 Cloud Volumes ONTAP 9.11.0 이상 시스템에서는 gp3 또는 io1 디스크를 사용할 때 Amazon EBS Elastic Volumes가 활성화되어 있습니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Elastic Volumes 지원에 대해 자세히 알아보세요"^]
. 집계된 모든 디스크의 크기는 동일해야 합니다.




[[disk-and-tiering-limits-by-ec2-instance]]
== EC2 인스턴스별 디스크 및 계층화 제한

용량 제한은 사용하는 EC2 인스턴스 유형 제품군과 단일 노드 시스템 또는 HA 쌍 사용 여부에 따라 다릅니다.

다음 참고 사항은 아래 표에 표시되는 숫자에 대한 세부 정보를 제공합니다.

* 디스크 제한은 사용자 데이터가 포함된 디스크에만 적용됩니다.
+
제한 사항에는 부팅 디스크와 루트 디스크가 포함되지 않습니다.

* 디스크만 사용할 경우와 디스크 및 콜드 데이터 계층화를 오브젝트 스토리지에 사용할 경우의 최대 시스템 용량이 나열됩니다.
* Cloud Volumes ONTAP는 EBS 볼륨을 디스크로 사용하며, 최대 디스크 크기는 16TiB입니다.




[[limits-for-different-deployment-modes-of-capacity-based-licensing]]
=== 용량 기반 라이센스의 다양한 배포 모드에 대한 제한 사항

다음 디스크 제한 사항은 용량 기반 라이센스 패키지를 사용하는 Cloud Volumes ONTAP 시스템에 적용됩니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP 라이센스 옵션에 대해 알아보십시오"^]


NOTE: 단일 노드 및 HA 구성에 대한 최대 시스템 용량 및 데이터 계층화 용량 제한에 대해서는 <<cap-license-aws>>을 참조하십시오.



==== 단일 노드

[cols="18,18,32,width=100%,options="]
|===


| 인스턴스 | 노드당 최대 디스크 수 | 디스크만 사용하는 최대 시스템 용량 


| c5, m5 및 r5 인스턴스 | 21 | 336 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^1^ | 304 TiB 
|===
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수는 더 적습니다.




==== HA 쌍

[cols="18,18,32,width=100%,options="]
|===


| 인스턴스 | 노드당 최대 디스크 수 | 디스크만 사용하는 최대 시스템 용량 


| c5, m5 및 r5 인스턴스 | 18 | 288 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^1^ | 256 TiB 
|===
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수는 더 적습니다.




[[limits-for-different-deployment-modes-of-node-based-licensing]]
=== 노드 기반 라이센스의 다양한 배포 모드에 대한 제한 사항

다음 디스크 제한 사항은 노드 기반 라이센스를 사용하는 Cloud Volumes ONTAP 시스템에 적용됩니다. 노드 기반 라이센스는 노드별로 Cloud Volumes ONTAP 라이센스를 부여할 수 있는 이전 세대 라이센스 모델입니다. 노드 기반 라이센스는 기존 고객에게 계속 제공됩니다.

Cloud Volumes ONTAP BYOL 단일 노드 또는 HA 쌍 시스템에 대해 여러 개의 노드 기반 라이센스를 구입하여 368TiB 이상의 용량을 할당할 수 있으며, 최대 테스트 및 지원되는 시스템 용량 제한인 2PiB까지 할당할 수 있습니다. 디스크 제한으로 인해 디스크만 사용하여 용량 제한에 도달하지 못할 수 있으므로 주의하십시오. 디스크 제한을 초과하려면 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 개체 스토리지로 계층화"^]. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Cloud Volumes ONTAP에 추가 시스템 라이센스를 추가하는 방법에 대해 알아보십시오"^]. Cloud Volumes ONTAP는 최대 테스트 및 지원되는 시스템 용량인 2PiB까지 지원하지만, 2PiB 제한을 초과하면 지원되지 않는 시스템 구성이 됩니다.

AWS Secret Cloud 및 Top Secret Cloud 리전에서는 Cloud Volumes ONTAP 9.12.1부터 여러 노드 기반 라이센스 구매가 지원됩니다.



==== PAYGO Premium이 포함된 단일 노드

[cols="18,18,32,32"]
|===
| 인스턴스 | 노드당 최대 디스크 수 | 디스크만 사용하는 최대 시스템 용량 | 디스크 및 데이터 계층화를 사용한 최대 시스템 용량 


| c5, m5 및 r5 인스턴스 | 21 ^1^ | 336 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB 
|===
. 21개의 데이터 디스크는 Cloud Volumes ONTAP의 _새로운_ 배포에 대한 제한입니다. 9.7 버전 이하로 생성된 시스템을 업그레이드하는 경우 해당 시스템은 22개의 디스크를 계속 지원합니다. 9.8 릴리스부터 코어 디스크가 추가됨에 따라 이러한 인스턴스 유형을 사용하는 새로운 시스템에서는 지원되는 데이터 디스크가 하나 줄어듭니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수는 더 적습니다.




==== BYOL을 사용하는 단일 노드

[cols="18,18,16,16,16,16"]
|===
| 인스턴스 | 노드당 최대 디스크 수 2+| 하나의 라이센스로 최대 시스템 용량 2+| 여러 라이센스를 사용한 최대 시스템 용량 


2+|  | *디스크만 해당* | *디스크 + 데이터 계층화* | *디스크만 해당* | *디스크 + 데이터 계층화* 


| c5, m5 및 r5 인스턴스 | 21 ^1^ | 336 TiB | 368 TiB | 336 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB | 304 TiB | 2 PiB 
|===
. 21개의 데이터 디스크는 Cloud Volumes ONTAP의 _새로운_ 배포에 대한 제한입니다. 9.7 버전 이하로 생성된 시스템을 업그레이드하는 경우 해당 시스템은 22개의 디스크를 계속 지원합니다. 9.8 릴리스부터 코어 디스크가 추가됨에 따라 이러한 인스턴스 유형을 사용하는 새로운 시스템에서는 지원되는 데이터 디스크가 하나 줄어듭니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수는 더 적습니다.




==== PAYGO Premium이 포함된 HA 쌍

[cols="18,18,32,32"]
|===
| 인스턴스 | 노드당 최대 디스크 수 | 디스크만 사용하는 최대 시스템 용량 | 디스크 및 데이터 계층화를 사용한 최대 시스템 용량 


| c5, m5 및 r5 인스턴스 | 18 ^1^ | 288 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256 TiB | 368 TiB 
|===
. 18개의 데이터 디스크는 Cloud Volumes ONTAP의 _새로운_ 배포에 대한 제한입니다. 9.7 버전 이하로 생성된 시스템을 업그레이드하는 경우 해당 시스템은 19개의 디스크를 계속 지원합니다. 9.8 릴리스부터 코어 디스크가 추가됨에 따라 이러한 인스턴스 유형을 사용하는 새로운 시스템에서는 지원되는 데이터 디스크가 하나 줄어듭니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수는 더 적습니다.




==== BYOL을 사용하는 HA 쌍

[cols="18,18,16,16,16,16"]
|===
| 인스턴스 | 노드당 최대 디스크 수 2+| 하나의 라이센스로 최대 시스템 용량 2+| 여러 라이센스를 사용한 최대 시스템 용량 


2+|  | *디스크만 해당* | *디스크 + 데이터 계층화* | *디스크만 해당* | *디스크 + 데이터 계층화* 


| c5, m5 및 r5 인스턴스 | 18 ^1^ | 288 TiB | 368 TiB | 288 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256 TiB | 368 TiB | 256 TiB | 2 PiB 
|===
. 18개의 데이터 디스크는 Cloud Volumes ONTAP의 _새로운_ 배포에 대한 제한입니다. 9.7 버전 이하로 생성된 시스템을 업그레이드하는 경우 해당 시스템은 19개의 디스크를 계속 지원합니다. 9.8 릴리스부터 코어 디스크가 추가됨에 따라 이러한 인스턴스 유형을 사용하는 새로운 시스템에서는 지원되는 데이터 디스크가 하나 줄어듭니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수는 더 적습니다.




[[storage-vm-limits]]
== 스토리지 VM 제한

일부 구성에서는 Cloud Volumes ONTAP용 추가 스토리지 VM(SVM)을 생성할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["추가 스토리지 VM을 생성하는 방법을 알아보세요."^].

[cols="40,60"]
|===
| 라이센스 유형 | 스토리지 VM 제한 


| *프리미엄*  a| 
총 24개의 스토리지 VM ^1,2^



| *용량 기반 PAYGO 또는 BYOL* ^3^  a| 
총 24개의 스토리지 VM ^1,2^



| *노드 기반 PAYGO*  a| 
* 데이터 제공을 위한 1개의 스토리지 VM
* 재해 복구를 위한 스토리지 VM 1개




| *노드 기반 BYOL* ^4^  a| 
* 총 24개의 스토리지 VM ^1,2^


|===
. 사용하는 EC2 인스턴스 유형에 따라 제한이 더 낮을 수 있습니다. 인스턴스별 제한은 아래 섹션에 나와 있습니다.
. 이 24개의 스토리지 VM은 데이터를 제공하거나 재해 복구(DR)용으로 구성할 수 있습니다.
. 용량 기반 라이선스의 경우 추가 스토리지 VM에 대한 추가 라이선스 비용은 없지만 스토리지 VM당 최소 4TiB 용량 요금이 부과됩니다. 예를 들어 스토리지 VM 2개를 생성하고 각각 2TiB의 프로비저닝된 용량이 있는 경우 총 8TiB가 청구됩니다.
. 노드 기반 BYOL의 경우, Cloud Volumes ONTAP에 기본적으로 제공되는 첫 번째 스토리지 VM을 초과하는 각 추가 _데이터 제공_ 스토리지 VM마다 추가 라이선스가 필요합니다. 스토리지 VM 추가 라이선스를 받으려면 담당 계정 팀에 문의하십시오.
+
재해 복구(DR)용으로 구성하는 스토리지 VM은 추가 라이센스가 필요하지 않지만(무료), 스토리지 VM 제한에 포함됩니다. 예를 들어, 데이터 제공 스토리지 VM이 12개이고 재해 복구용으로 구성된 스토리지 VM이 12개인 경우, 제한에 도달하여 추가 스토리지 VM을 생성할 수 없습니다.





[[storage-vm-limit-by-ec2-instance-type]]
=== EC2 인스턴스 유형별 Storage VM 제한

추가 스토리지 VM을 생성할 때는 포트 e0a에 프라이빗 IP 주소를 할당해야 합니다. 아래 표는 인터페이스당 최대 프라이빗 IP 수와 Cloud Volumes ONTAP 배포 후 포트 e0a에서 사용 가능한 IP 주소 수를 보여줍니다. 사용 가능한 IP 주소 수는 해당 구성의 최대 스토리지 VM 수에 직접적인 영향을 미칩니다.

아래에 나열된 인스턴스는 c5, m5 및 r5 인스턴스 제품군용입니다.

[cols="6*"]
|===
| 구성 | 인스턴스 유형 | 인터페이스당 최대 프라이빗 IP | 배포 후 남은 IP ^1^ | 관리 LIF가 없는 최대 스토리지 VM ^2,3^ | 관리 LIF ^2,3^을 사용하는 최대 스토리지 VM 


.9+| *단일 노드* | *.xlarge | 15 | 9 | 10 | 5 


| *.2xlarge | 15 | 9 | 10 | 5 


| *.4xlarge | 30 | 24 | 24 | 12 


| *.8xlarge | 30 | 24 | 24 | 12 


| *.9xlarge | 30 | 24 | 24 | 12 


| *.12xlarge | 30 | 24 | 24 | 12 


| *.16xlarge | 50 | 44 | 24 | 12 


| *.18xlarge | 50 | 44 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *단일 AZ의 HA 쌍* | *.xlarge | 15 | 10 | 11 | 5 


| *.2xlarge | 15 | 10 | 11 | 5 


| *.4xlarge | 30 | 25 | 24 | 12 


| *.8xlarge | 30 | 25 | 24 | 12 


| *.9xlarge | 30 | 25 | 24 | 12 


| *.12xlarge | 30 | 25 | 24 | 12 


| *.16xlarge | 50 | 45 | 24 | 12 


| *.18xlarge | 50 | 45 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *다중 AZ의 HA 쌍* | *.xlarge | 15 | 12 | 13 | 13 


| *.2xlarge | 15 | 12 | 13 | 13 


| *.4xlarge | 30 | 27 | 24 | 24 


| *.8xlarge | 30 | 27 | 24 | 24 


| *.9xlarge | 30 | 27 | 24 | 24 


| *.12xlarge | 30 | 27 | 24 | 24 


| *.16xlarge | 50 | 47 | 24 | 24 


| *.18xlarge | 50 | 47 | 24 | 24 


| *.24xlarge | 50 | 44 | 24 | 12 
|===
. 이 숫자는 Cloud Volumes ONTAP이 배포 및 설정된 후 포트 e0a에서 사용 가능한 _남은_ 프라이빗 IP 주소 수를 나타냅니다. 예를 들어, *.2xlarge 시스템은 네트워크 인터페이스당 최대 15개의 IP 주소를 지원합니다. 단일 AZ에 HA 쌍이 배포되면 포트 e0a에 5개의 프라이빗 IP 주소가 할당됩니다. 결과적으로 *.2xlarge 인스턴스 유형을 사용하는 HA 쌍에는 추가 스토리지 VM에 사용할 수 있는 10개의 프라이빗 IP 주소가 남게 됩니다.
. 이 열에 표시된 숫자는 Console에서 기본적으로 생성하는 초기 스토리지 VM을 포함합니다. 예를 들어 이 열에 24가 표시되면 23개의 추가 스토리지 VM을 생성하여 총 24개를 만들 수 있음을 의미합니다.
. 스토리지 VM용 관리 LIF는 선택 사항입니다. 관리 LIF는 SnapCenter와 같은 관리 툴에 대한 연결을 제공합니다.
+
프라이빗 IP 주소가 필요하므로 생성할 수 있는 추가 스토리지 VM의 수가 제한됩니다. 단, 여러 가용 영역에 걸쳐 있는 HA 쌍은 예외입니다. 이 경우 관리 LIF의 IP 주소는 플로팅 IP 주소이므로 프라이빗 IP 주소 제한에 포함되지 않습니다.





[[file-and-volume-limits]]
== 파일 및 볼륨 제한

[cols="22,22,56"]
|===
| 논리적 스토리지 | 매개변수 | 제한 


.2+| *파일* | 최대 크기 ^2^ | 128 TB 


| 볼륨당 최대값 | 볼륨 크기에 따라 최대 20억 


| *FlexClone 볼륨* | 계층적 클론 깊이 ^1^ | 499 


.3+| *FlexVol 볼륨* | 노드당 최대값 | 500 


| 최소 크기 | 20 MB 


| 최대 크기 ^3^ | 300 TiB 


| * Qtree * | FlexVol 볼륨당 최대 | 4,995 


| *Snapshot 복사본* | FlexVol 볼륨당 최대 | 1,023 
|===
. 계층적 클론 깊이는 단일 FlexVol 볼륨에서 생성할 수 있는 중첩된 FlexClone 볼륨 계층 구조의 최대 깊이입니다.
. ONTAP 9.12.1P2부터 제한은 128TB입니다. ONTAP 9.11.1 및 이전 버전에서는 제한이 16TB입니다.
. FlexVol 볼륨 생성은 최대 300TiB 크기까지 지원되며, 다음 도구 및 최소 버전이 필요합니다.
+
** Cloud Volumes ONTAP 9.12.1 P2 및 9.13.0 P2부터 System Manager 및 ONTAP CLI
** Cloud Volumes ONTAP 9.13.1부터






[[iscsi-storage-limits]]
== iSCSI 스토리지 제한

[cols="3*"]
|===
| iSCSI 스토리지 | 매개변수 | 제한 


.4+| * LUN * | 노드당 최대값 | 1,024 


| LUN 맵의 최대 수 | 1,024 


| 최대 크기 | 16 TiB 


| 볼륨당 최대값 | 512 


| *igroup* | 노드당 최대값 | 256 


.2+| *이니시에이터* | 노드당 최대값 | 512 


| igroup당 최대값 | 128 


| *iSCSI 세션* | 노드당 최대값 | 1,024 


.2+| *LIF* | 포트당 최대 | 32 


| 포트셋당 최대 | 32 


| *포트셋* | 노드당 최대값 | 256 
|===