---
sidebar: sidebar 
permalink: reference-worm-snaplock.html 
keywords: WORM, SnapLock, Snapshot copies, 
summary: 'Cloud Volumes ONTAP 시스템에서 한 번 쓰고 여러 번 읽을 수 있는(WORM) 파일의 변조 방지 스냅샷 사본을 만들고 특정 보존 기간 동안 수정되지 않은 형태로 스냅샷을 보관할 수 있습니다.' 
---
= Cloud Volumes ONTAP 에서 WORM 파일의 변조 방지 스냅샷 복사본을 만듭니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 시스템에서 한 번 쓰고 여러 번 읽을 수 있는(WORM) 파일의 변조 방지 스냅샷 사본을 만들고 특정 보존 기간 동안 수정되지 않은 형태로 스냅샷을 보관할 수 있습니다.  이 기능은 SnapLock 기술을 기반으로 하며, 데이터 보호 및 규정 준수를 한층 더 강화합니다.

.시작하기 전에
스냅샷 복사본을 만드는 데 사용하는 볼륨이 SnapLock 볼륨인지 확인하세요.  볼륨에서 SnapLock 보호를 활성화하는 방법에 대한 자세한 내용은 다음을 참조하십시오. https://docs.netapp.com/us-en/ontap/snaplock/snaplock-config-overview-concept.html["ONTAP 설명서: SnapLock 구성"^] .

.단계
. SnapLock 볼륨에서 스냅샷 복사본을 만듭니다.  CLI 또는 시스템 관리자를 사용하여 스냅샷 복사본을 만드는 방법에 대한 자세한 내용은 다음을 참조하십시오. https://docs.netapp.com/us-en/ontap/data-protection/manage-local-snapshot-copies-concept.html["ONTAP 설명서: 로컬 스냅샷 복사본 관리 개요"^] .
+
스냅샷 복사본은 볼륨의 WORM 속성을 상속하므로 변조가 불가능합니다.  기본 SnapLock 기술은 지정된 보존 기간이 경과할 때까지 스냅샷이 편집 및 삭제되지 않도록 보호합니다.

. 스냅샷을 편집해야 하는 경우 보존 기간을 수정할 수 있습니다.  자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/snaplock/set-retention-period-task.html#set-the-default-retention-period["ONTAP 문서: 보존 시간 설정"^] .



NOTE: 스냅샷 사본은 특정 보존 기간 동안 보호되지만, Cloud Volumes ONTAP 의 WORM 스토리지는 "신뢰할 수 있는 스토리지 관리자" 모델에서 작동하므로 클러스터 관리자가 소스 볼륨을 삭제할 수 있습니다.  또한 신뢰할 수 있는 클라우드 관리자는 클라우드 스토리지 리소스를 조작하여 WORM 데이터를 삭제할 수 있습니다.

.관련 링크
* WORM에 대한 자세한 내용은 다음을 참조하세요.link:concept-worm.html["Cloud Volumes ONTAP 의 WORM 스토리지에 대해 알아보세요"] .
* SnapLock 볼륨 충전에 대한 정보는 다음을 참조하세요.link:concept-licensing-charging.html["Cloud Volumes ONTAP 의 라이선싱 및 요금 청구"] .

