---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support, SMB CA in CVO 
summary: 이 페이지에서는 NetApp이 클라우드 공급업체와 협력하여 발생할 수 있는 문제를 해결하는 방법을 설명합니다. 
---
= Cloud Volumes ONTAP과 클라우드 제공업체 간의 통합
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp이 클라우드 제공업체와 협력하여 잠재적인 문제를 해결하는 방법을 알아보세요.



[[collaborative-support-best-practices]]
== 협업 지원 모범 사례

NetApp은 라이선스 사용자에게 지원을 제공하기 위해 최선을 다하며, 라이선스 사용자가 보고하는 Cloud Volumes ONTAP 관련 기술 지원 문제를 해결하기 위해 상업적으로 합리적인 노력을 기울일 것입니다. NetApp과 해당 클라우드 제공업체는 서로의 라이선스 소프트웨어 또는 인프라에 대해 직접적인 지원 의무를 지지 않습니다.

NetApp은 해당 클라우드 공급자 서비스로 인해 발생할 수 있는 고객 기술 문제에 대해 해당 클라우드 공급자와 연결하기 위한 도구를 구현했습니다. 그러나 원활한 지원 흐름을 유지하는 가장 좋은 방법은 고객이 (i) NetApp 및 해당 클라우드 공급자 모두와 현재 지원 계약을 유지하고 (ii) 기술 문제가 발생하고 고객이 어떤 제품 또는 서비스가 해당 기술 문제를 일으키는지 명확히 해야 할 때 NetApp 및 해당 클라우드 공급자 모두와 공동 에스컬레이션 회의를 조율하는 것입니다.



[[azure-maintenance-events]]
== Azure 유지보수 이벤트

Microsoft는 Cloud Volumes ONTAP VM에 영향을 줄 수 있는 Azure 가상 머신(VM) 인프라에 대한 유지 관리 이벤트를 예약하고 프로그램 방식으로 공지합니다. 이러한 이벤트는 유지보수 윈도우 15분 전에 공지됩니다.

Cloud Volumes ONTAP 고가용성(HA) 쌍에 대해서는 유지 관리 이벤트에 대한 특별 처리가 지원됩니다. 애플리케이션의 안정적인 작동을 유지하기 위해 안정성을 우선시하는 예방적 테이크오버를 수행하며, 15초 이상 연결이 끊어지면 페일오버 기능이 비활성화됩니다.

유지보수 윈도우가 공지되면 대상 노드의 파트너 노드가 제어권을 인계받습니다. 유지보수가 완료되면 제어권 반환이 시작됩니다. 제어권 반환 후 HA 쌍은 정상 상태로 복귀할 것으로 예상됩니다. 만약 정상 상태로 복귀하지 않을 경우 NetApp 기술 지원팀에 문의하십시오. 유지보수 이벤트는 HA 쌍의 VM 중 한 대에만 적용되며, 일반적으로 두 노드 모두 비교적 짧은 시간 내에 대상이 됩니다.

Cloud Volumes ONTAP의 비연속적 가용성 CIFS 공유를 사용하는 CIFS/SMB 클라이언트는 테이크오버가 발생하거나 세션이 사용 중인 애그리게이트가 애그리게이트의 홈 노드로 반환될 때 세션이 끊어집니다. 이는 CIFS/SMB 프로토콜 자체의 제약 사항입니다. 테이크오버 및 반환으로 인한 문제를 방지하려면 승인된 타사 제품을 사용하십시오. 추가 지원이 필요하면 NetApp 지원팀에 문의하십시오.


NOTE: https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["지속적으로 사용 가능한 SMB 공유"^] 무중단 운영은 Cloud Volumes ONTAP에서 지원되지 않습니다.
