---
sidebar: sidebar 
permalink: task-getting-started-gcp.html 
keywords: google cloud platform, gcp, cloud manager, deploy the Console, launch the Console, create the Console, getting started, networking, gcp networking, service account, tiering, data tiering, bucket, fabricpool, cloud backup, storage access key, gcp role, role, iam role, permissions, gcp permissions, cloud backup, the Console 
summary: 몇 단계만 거치면 Google Cloud용 Cloud Volumes ONTAP 시작할 수 있습니다. 
---
= Google Cloud에서 Cloud Volumes ONTAP 배포 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP를 배포하려면 먼저 Google Cloud 구독 및 Cloud Volumes ONTAP 라이선스에 대한 정보를 알아야 합니다. 또한 Google Cloud 프로젝트 및 조직에 대해 NetApp Console 에이전트가 생성되었는지 확인해야 합니다. 이 항목의 대부분 내용은 Cloud Volumes ONTAP를 배포하기 전에 Console 설정의 일부로 수행해야 합니다.

[cols="20,35,25,25"]
|===
| 일 | 설명 | 참조 | 프라이빗 환경 배포 관련 참고 사항 


 a| 
콘솔 에이전트 생성
 a| 
콘솔 에이전트가 아직 없는 경우 Cloud Volumes ONTAP를 배포하기 전에 먼저 생성하십시오. 인터넷에 접속할 수 없는 서브넷에 배포하는 경우 콘솔 에이전트를 수동으로 설치하고 해당 에이전트에서 실행되는 NetApp Console에 액세스하십시오.
 a| 
콘솔 설정 가이드를 참조하십시오: https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-google-gcloud.html["Google Cloud에서 Console 에이전트 생성"^]
 a| 
인터넷에 접속할 수 없는 서브넷에 배포하는 경우 콘솔 에이전트를 수동으로 설치하고 해당 콘솔 에이전트에서 실행되는 NetApp Console 사용자 인터페이스에 액세스하십시오. 콘솔 설정 가이드를 참조하십시오. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["인터넷 연결 없이 Console 에이전트를 수동으로 설치합니다."^]



 a| 
구성을 계획하세요
 a| 
콘솔은 사용자의 작업 부하 요구 사항에 맞는 미리 구성된 패키지를 제공하거나 사용자가 직접 구성을 만들 수도 있습니다.  원하는 구성을 선택하는 경우, 사용 가능한 옵션을 이해해야 합니다.
 a| 
link:task-planning-your-config-gcp.html["구성을 계획하세요"]
 a| 
프라이빗 환경 모드 배포에도 유사한 계획 고려 사항이 필요합니다.



 a| 
네트워킹을 설정하세요
 a| 
. VPC와 서브넷이 콘솔 에이전트와 Cloud Volumes ONTAP 간의 연결을 지원하는지 확인하세요.
. 데이터 계층화를 활성화하려면 Private Google Access를 위한 Cloud Volumes ONTAP 서브넷을 구성하세요.
. HA 쌍을 배포하는 경우 각각 자체 서브넷이 있는 4개의 VPC가 있는지 확인하세요.
. 공유 VPC를 사용하는 경우 콘솔 에이전트 서비스 계정에 _Compute Network User_ 역할을 제공합니다.
. NetApp AutoSupport 에 대해 대상 VPC에서 아웃바운드 인터넷 액세스를 활성화합니다.

 a| 
다음을 참조하십시오.

* link:reference-networking-gcp.html["Google 클라우드용 네트워킹 요구 사항"]
* Google Cloud 문서를 참조하십시오. https://cloud.google.com/vpc/docs/configure-private-google-access["Google 비공개 액세스 구성"^]

 a| 
AutoSupport에 대한 아웃바운드 인터넷 액세스는 필요하지 않습니다. 다른 네트워크 요구 사항은 모두 동일합니다.



 a| 
서비스 계정 설정
 a| 
Cloud Volumes ONTAP 사용하려면 Google Cloud 서비스 계정이 필요합니다. 이 계정은 데이터 계층화를 활성화하여 콜드 데이터를 Google Cloud의 저렴한 객체 스토리지로 계층화하고, NetApp Backup and Recovery를 활성화하여 볼륨을 저렴한 객체 스토리지에 백업하는 데 사용됩니다.
 a| 
* link:task-creating-gcp-service-account.html["서비스 계정 설정"]
* link:concept-data-tiering.html["데이터 계층화에 대해 알아보기"]
* 다음을 참조하십시오 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["NetApp Backup and Recovery 문서"^]

 a| 
프라이빗 환경 배포에는 추가적인 고려 사항이 없습니다.



 a| 
Google Cloud API 활성화
 a| 
프로젝트에서 필요한 Google Cloud API를 사용 설정하세요. 콘솔 에이전트를 생성하는 과정에서 이미 이러한 API를 사용 설정했을 수도 있습니다.
 a| 
Google Cloud 문서를 참조하세요: https://cloud.google.com/apis/docs/getting-started#enabling_apis["Google Cloud API 활성화"^]
 a| 
API를 활성화해야 합니다. 클라우드 관리자와 협력하여 프라이빗 환경에서 필요한 API를 활성화하십시오.



 a| 
콘솔에서 Cloud Volumes ONTAP 배포
 a| 
사전 준비 작업을 모두 완료했으면 마법사의 단계를 따라 Google Cloud에 Cloud Volumes ONTAP을 배포할 수 있습니다.
 a| 
다음을 참조하십시오.

* link:task-quick-deploy-gcp.html["빠른 생성 기능을 사용하여 Cloud Volumes ONTAP 배포"]
* link:task-deploying-gcp.html["고급 옵션을 사용하여 Cloud Volumes ONTAP 배포"]

 a| 
배포를 시작하기 전에 NetApp에서 Cloud Volumes ONTAP 라이선스를 구매했는지 확인하십시오. 프라이빗 모드 배포에는 노드 기반 BYOL 라이선스가 필요합니다. 마켓플레이스 구독을 통한 Cloud Volumes ONTAP 사용량 청구는 지원되지 않습니다. NetApp에서 라이선스 파일을 받아 배포 중에 업로드하십시오. 자세한 내용은 다음을 참조하십시오.

* link:concept-license-management.html["노드 기반 BYOL에 대한 라이선스 관리"]
* link:task-manage-node-licenses.html["노드 기반 BYOL 라이선스 관리"]
* link:task-quick-deploy-gcp.html["빠른 생성 기능을 사용하여 Cloud Volumes ONTAP 배포"]
* link:task-deploying-gcp.html["고급 옵션을 사용하여 Cloud Volumes ONTAP 배포"]


|===
.관련 링크
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["콘솔 에이전트 생성"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Linux 호스트에 콘솔 에이전트 소프트웨어 설치"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["콘솔 에이전트에 대한 Google Cloud 권한"^]

