---
sidebar: sidebar 
permalink: task-convert-node-capacity.html 
keywords: license conversion, convert node-based to capacity based, by-node to by-capacity, license conversion for node based, BlueXP, Console 
summary: '노드 기반 라이선스의 사용 가능 기간 종료(EOA) 후에는 라이선스 변환 도구를 사용하여 용량 기반 라이선스로 전환해야 합니다.' 
---
= Cloud Volumes ONTAP 노드 기반 라이선스를 용량 기반 라이선스로 변환
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 기반 라이선스의 사용 가능 기간 종료(EOA) 후에는 NetApp 콘솔의 라이선스 변환 도구를 사용하여 용량 기반 라이선스로 전환해야 합니다.

연간 또는 장기 약정의 경우 NetApp EOA 날짜(2024년 11월 11일) 또는 라이선스 만료일 전에 NetApp 담당자에게 연락하여 전환에 필요한 전제 조건이 충족되었는지 확인하는 것을 권장합니다.  Cloud Volumes ONTAP 노드에 대한 장기 계약이 없고 온디맨드 PAYGO(Pay-as-you-go) 구독으로 시스템을 실행하는 경우 2024년 12월 31일 지원 종료(EOS) 전에 전환을 계획하는 것이 중요합니다.  두 경우 모두 NetApp 콘솔의 라이선스 변환 도구를 사용하여 원활하게 전환하기 전에 시스템이 요구 사항을 충족하는지 확인해야 합니다.

EOA 및 EOS에 대한 정보는 다음을 참조하세요.link:concept-licensing.html#end-of-availability-of-node-based-licenses["노드 기반 라이선스 제공 종료"] .

.이 작업에 관하여
* 라이선스 변환 도구를 사용하면 노드 기반에서 용량 기반 라이선스 모델로의 전환이 현장에서 온라인에서 수행되므로 데이터 마이그레이션이나 추가 클라우드 리소스 프로비저닝이 필요 없습니다.
* 이는 중단 없는 작업이므로 서비스 중단이나 애플리케이션 가동 중지가 발생하지 않습니다.
* Cloud Volumes ONTAP 시스템의 계정 및 애플리케이션 데이터는 그대로 유지됩니다.
* 기본 클라우드 리소스는 변환 후에도 영향을 받지 않습니다.
* 라이선스 변환 도구는 단일 노드, 단일 가용성 영역(AZ)의 고가용성(HA), 여러 AZ의 HA, 자체 라이선스 사용(BYOL), PAYGO 등 모든 배포 유형을 지원합니다.
* 이 도구는 모든 노드 기반 라이선스를 소스로, 모든 용량 기반 라이선스를 대상으로 지원합니다. 예를 들어 PAYGO Standard 노드 기반 라이선스가 있는 경우 마켓플레이스를 통해 구매한 모든 용량 기반 라이선스로 변환할 수 있습니다. NetApp BYOL 라이선스 구매, 연장 및 갱신을 제한하고 있습니다. 자세한 내용은 다음을 참조하세요.  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAP 에 대한 BYOL 라이선싱의 제한된 가용성"^] .
* 이러한 변환은 AWS, Azure, Google Cloud 등 모든 클라우드 제공업체에서 지원됩니다.
* 변환 후 노드 기반 라이센스의 일련 번호는 용량 기반 형식으로 대체됩니다.  이 작업은 변환의 일부로 수행되며 NetApp 지원 사이트(NSS) 계정에 반영됩니다.
* 용량 기반 모델로 전환하면 데이터는 노드 기반 라이선싱과 동일한 위치에 계속 보관됩니다.  이러한 접근 방식은 데이터 배치에 중단이 발생하지 않도록 보장하며, 전환 과정 전반에 걸쳐 데이터 주권 원칙을 지지합니다.


.시작하기 전에
* 고객 액세스 또는 관리자 액세스 권한이 있는 NSS 계정이 있어야 합니다.
* 귀하의 NSS 계정은 콘솔에 액세스하는 데 사용한 사용자 자격 증명으로 등록되어야 합니다.
* Cloud Volumes ONTAP 시스템은 고객 액세스 또는 관리자 액세스 권한이 있는 NSS 계정에 연결되어야 합니다.
* BYOL 라이선스 또는 마켓플레이스 구독 등 유효한 용량 기반 라이선스가 있어야 합니다.
* 귀하의 계정에는 용량 기반 라이선스가 사용 가능해야 합니다.  이 라이선스는 콘솔의 *라이선스 및 구독*에서 사용할 수 있는 마켓플레이스 구독 또는 BYOL/개인 제공 패키지일 수 있습니다.
* 목적지 패키지를 선택하기 전에 다음 기준을 이해하세요.
+
** 계정에 용량 기반 BYOL 라이선스가 있는 경우 선택한 대상 패키지는 계정의 BYOL 용량 기반 라이선스와 일치해야 합니다.
+
*** 언제 `Professional` 대상 패키지로 선택된 경우 계정에 Professional 패키지가 포함된 BYOL 라이선스가 있어야 합니다.
*** 언제 `Essentials` 대상 패키지로 선택된 경우, 계정에 Essentials 패키지가 포함된 BYOL 라이선스가 있어야 합니다.


** 대상 패키지가 계정의 BYOL 라이선스 가용성과 일치하지 않으면 용량 기반 라이선스에 선택한 패키지가 포함되지 않을 수 있습니다.  이 경우 마켓플레이스 구독을 통해 요금이 청구됩니다.
** 용량 기반 BYOL 라이선스가 없고 마켓플레이스 구독만 있는 경우, 선택한 패키지가 용량 기반 마켓플레이스 구독에 포함되어 있는지 확인해야 합니다.
** 기존 용량 기반 라이선스에 충분한 용량이 없고, 추가 용량 사용에 대해 요금을 청구하는 마켓플레이스 구독이 있는 경우, 마켓플레이스 구독을 통해 추가 용량에 대한 요금이 청구됩니다.
** 기존 용량 기반 라이선스에 충분한 용량이 없고, 추가 용량 사용에 대한 요금을 청구할 마켓플레이스 구독이 없으면 변환이 이루어질 수 없습니다.  추가 용량에 대한 요금을 청구하거나 현재 라이선스의 사용 가능한 용량을 확장하려면 마켓플레이스 구독을 추가해야 합니다.
** 대상 패키지가 계정의 BYOL 라이선스 가용성과 맞지 않고 기존 용량 기반 라이선스에 충분한 용량이 없는 경우 마켓플레이스 구독을 통해 요금이 청구됩니다.





NOTE: 이러한 요구 사항 중 하나라도 충족되지 않으면 라이센스 전환이 이루어지지 않습니다.  특정한 경우 라이센스는 변환되지만 사용할 수 없을 수도 있습니다.  정보 아이콘을 클릭하여 문제를 파악하고 시정 조치를 취하세요.

.단계
. *시스템* 페이지에서 라이선스 유형을 수정하려는 시스템의 이름을 두 번 클릭합니다.
. 개요 탭에서 기능 패널을 클릭합니다.
. *충전 방법* 옆에 있는 연필 아이콘을 확인하세요.  시스템의 충전 방법이 다음과 같은 경우 `Node Based` , 용량별 요금으로 변환할 수 있습니다.
+

TIP: Cloud Volumes ONTAP 시스템이 이미 용량에 따라 요금이 청구되었거나 요구 사항 중 하나라도 충족되지 않으면 아이콘이 비활성화됩니다.

. *노드 기반 라이선스를 용량 기반으로 변환* 화면에서 시스템 이름과 소스 라이선스 세부 정보를 확인합니다.
. 기존 라이선스를 변환할 대상 패키지를 선택하세요.
+
** 골자.  기본값은 `Essentials` .
** 전문적인


. BYOL 라이선스가 있는 경우 변환이 완료된 후 콘솔에서 노드 기반 라이선스를 삭제하기 위한 확인란을 선택할 수 있습니다.  변환이 진행 중이면 이 확인란을 선택해도 콘솔에서 라이센스가 제거되지 않습니다.  이 옵션은 마켓플레이스 구독에는 사용할 수 없습니다.
. 변경 사항의 의미를 이해했음을 확인하려면 확인란을 선택한 다음 *계속*을 클릭합니다.


.당신이 완료한 후
새로운 라이선스 일련 번호를 보고 콘솔의 *라이선스 및 구독* 메뉴에서 변경 사항을 확인하세요.



== 다양한 하이퍼스칼라 가격 책정

가격에 대한 자세한 내용은 다음을 참조하세요. https://bluexp.netapp.com/pricing/["NetApp 콘솔 웹사이트"^] .

특정 하이퍼스칼라에 대한 개인 제안에 대한 자세한 내용은 다음 주소로 문의하세요.

* AWS - awspo@netapp.com
* Azure - azurepo@netapp.com
* 구글 클라우드 - gcppo@netapp.com

