---
sidebar: sidebar 
permalink: task-azure-high-availability-mode.html 
keywords: high availability mode, EnableHighAvailabilityMode, action required, nfsv4 
summary: 계획되지 않은 장애 조치 시간을 줄이고 Cloud Volumes ONTAP 에 대한 NFSv4 지원을 활성화하려면 Microsoft Azure의 고가용성 모드를 활성화해야 합니다. 
---
= Azure에서 Cloud Volumes ONTAP 에 대해 고가용성 모드 활성화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
계획되지 않은 장애 조치 시간을 줄이고 Cloud Volumes ONTAP 에 대한 NFSv4 지원을 활성화하려면 Microsoft Azure의 고가용성(HA) 모드를 활성화해야 합니다.  이 모드에서는 Cloud Volumes ONTAP HA 노드가 CIFS 및 NFSv4 클라이언트에서 계획되지 않은 장애 조치 중에 낮은(60초) 복구 시간 목표(RTO)를 달성할 수 있습니다.

Cloud Volumes ONTAP 9.10.1부터 Microsoft Azure에서 실행되는 Cloud Volumes ONTAP HA 쌍에 대한 계획되지 않은 장애 조치 시간을 줄이고 NFSv4에 대한 지원을 추가했습니다.  이러한 향상된 기능을 Cloud Volumes ONTAP 에 적용하려면 Azure 구독에서 고가용성 기능을 활성화해야 합니다.

Azure 구독에서 해당 기능을 활성화해야 하는 경우 NetApp Console 이러한 세부 정보를 묻습니다.

다음 사항에 유의하세요.

* Cloud Volumes ONTAP HA 쌍의 고가용성에는 문제가 없습니다.  이 Azure 기능은 ONTAP 과 함께 작동하여 계획되지 않은 장애 조치 이벤트로 인해 NFS 프로토콜에 대한 클라이언트 관찰 애플리케이션 중단 시간을 줄입니다.
* 이 기능을 활성화해도 Cloud Volumes ONTAP HA 쌍은 중단되지 않습니다.
* Azure 구독에서 이 기능을 활성화해도 다른 VM에는 문제가 발생하지 않습니다.
* Cloud Volumes ONTAP CIFS 및 NFS 클라이언트에서 클러스터 및 SVM 관리 LIF의 장애 조치 중에 내부 Azure Load Balancer를 사용합니다.
* HA 모드가 활성화되면 콘솔은 12시간마다 시스템을 검사하여 내부 Azure Load Balancer 규칙을 업데이트합니다.


"소유자" 권한이 있는 Azure 사용자는 Azure CLI에서 해당 기능을 활성화할 수 있습니다.

.단계
. https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart["Azure Portal에서 Azure Cloud Shell에 액세스"^]
. 고가용성 모드 기능을 등록하세요:
+
[source, azurecli]
----
az account set -s AZURE_SUBSCRIPTION_NAME_OR_ID
az feature register --name EnableHighAvailabilityMode --namespace Microsoft.Network
az provider register -n Microsoft.Network
----
. 선택적으로 해당 기능이 등록되었는지 확인하세요.
+
[source, azurecli]
----
az feature show --name EnableHighAvailabilityMode --namespace Microsoft.Network
----
+
Azure CLI는 다음과 유사한 결과를 반환해야 합니다.

+
[listing]
----
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Features/providers/Microsoft.Network/features/EnableHighAvailabilityMode",
  "name": "Microsoft.Network/EnableHighAvailabilityMode",
  "properties": {
    "state": "Registered"
  },
  "type": "Microsoft.Features/providers/features"
}
----

