---
sidebar: sidebar 
permalink: task-getting-started-aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create, console 
summary: AWS에 Cloud Volumes ONTAP을 배포하기 위한 필수 조건을 모두 충족했는지 확인하십시오. 
---
= AWS의 Cloud Volumes ONTAP 배포 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP를 배포하려면 먼저 AWS 구독 및 Cloud Volumes ONTAP 라이선스에 대한 정보를 알아야 합니다. 또한 AWS 계정에 대해 생성된 NetApp Console 에이전트가 있는지 확인해야 합니다. 이 항목의 대부분 내용은 Cloud Volumes ONTAP를 배포하기 전에 Console 설정의 일부로 수행해야 합니다.

[cols="20,35,25,25"]
|===
| 일 | 설명 | 참조 | 프라이빗 환경 배포 관련 참고 사항 


 a| 
콘솔 에이전트 생성
 a| 
콘솔 에이전트가 아직 없는 경우 Cloud Volumes ONTAP를 배포하기 전에 먼저 생성하십시오. 인터넷에 접속할 수 없는 서브넷에 배포하는 경우 콘솔 에이전트를 수동으로 설치하고 해당 에이전트에서 실행되는 NetApp Console에 액세스하십시오.
 a| 
콘솔 설정 가이드를 참조하십시오: https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["AWS에서 Console 에이전트 생성"^]
 a| 
인터넷에 접속할 수 없는 서브넷에 배포하는 경우 콘솔 에이전트를 수동으로 설치하고 해당 콘솔 에이전트에서 실행되는 NetApp Console 사용자 인터페이스에 액세스하십시오. 콘솔 설정 가이드를 참조하십시오. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["인터넷 연결 없이 Console 에이전트를 수동으로 설치합니다."^]



 a| 
구성을 계획하세요
 a| 
콘솔은 사용자의 작업 부하 요구 사항에 맞는 미리 구성된 패키지를 제공하거나 사용자가 직접 구성을 만들 수도 있습니다.  원하는 구성을 선택하는 경우, 사용 가능한 옵션을 이해해야 합니다.
 a| 
link:task-planning-your-config.html["구성을 계획하세요"]
 a| 
프라이빗 환경 모드 배포에도 유사한 계획 고려 사항이 필요합니다.



 a| 
네트워킹을 설정하세요
 a| 
. VPC 및 서브넷이 콘솔 에이전트와 Cloud Volumes ONTAP 간의 연결을 지원하는지 확인하십시오.
. AutoSupport에 대한 아웃바운드 인터넷 액세스를 활성화합니다.
. 데이터 계층화를 위해 Amazon S3에 대한 VPC 엔드포인트를 설정합니다. Cloud Volumes ONTAP에서 저렴한 객체 스토리지로 콜드 데이터를 계층화하려면 VPC 엔드포인트가 필요합니다.

 a| 
link:reference-networking-aws.html["AWS 네트워킹 요구 사항"]
 a| 
AutoSupport에 대한 아웃바운드 인터넷 액세스는 필요하지 않습니다. 다른 네트워크 요구 사항은 모두 동일합니다.



 a| 
AWS KMS 설정
 a| 
Cloud Volumes ONTAP에서 Amazon 암호화를 사용하려면 활성 고객 마스터 키(CMK)가 있는지 확인하고 Console 에이전트용 IAM 역할을 키 사용자로 추가하도록 키 정책을 수정해야 합니다.
 a| 
link:task-setting-up-kms.html["AWS KMS 설정"]
 a| 
프라이빗 환경 모드 배포에도 유사한 절차가 적용됩니다.



 a| 
콘솔에서 Cloud Volumes ONTAP 배포
 a| 
사전 준비 작업을 모두 완료했으면 마법사의 단계를 따라 AWS에 Cloud Volumes ONTAP을 배포할 수 있습니다.
 a| 
* link:task-quick-deploy-aws.html["빠른 생성 기능을 사용하여 Cloud Volumes ONTAP 배포"]
* link:task-deploying-otc-aws.html["고급 옵션을 사용하여 Cloud Volumes ONTAP 배포"]

 a| 
배포를 시작하기 전에 NetApp에서 Cloud Volumes ONTAP 라이선스를 구매했는지 확인하십시오. 프라이빗 모드 배포에는 노드 기반 BYOL 라이선스가 필요합니다. 마켓플레이스 구독을 통한 Cloud Volumes ONTAP 사용량 청구는 지원되지 않습니다. NetApp에서 라이선스 파일을 받아 배포 중에 업로드하십시오. 자세한 내용은 다음을 참조하십시오.

* link:concept-license-management.html["노드 기반 BYOL에 대한 라이선스 관리"]
* link:task-manage-node-licenses.html["노드 기반 BYOL 라이선스 관리"]
* link:task-quick-deploy-aws.html["빠른 생성 기능을 사용하여 Cloud Volumes ONTAP 배포"]
* link:task-deploying-otc-aws.html["고급 옵션을 사용하여 Cloud Volumes ONTAP 배포"]


|===
.관련 링크
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-bluexp.html["AWS용 콘솔 에이전트 만들기"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html["AWS Marketplace에서 콘솔 에이전트 만들기"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["온프레미스에 콘솔 에이전트 설치 및 설정"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["콘솔 에이전트에 대한 AWS 권한"^]

