---
sidebar: sidebar 
permalink: task-planning-your-config-azure.html 
keywords: license, disk, storage, size, write speed, volume usage, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, premium storage, standard storage, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported vm type, supported virtual machines, supported virtual machine types, supported instances, space, size, azure, disk size 
summary: Azure에 Cloud Volumes ONTAP 배포할 때 워크로드 요구 사항에 맞는 미리 구성된 시스템을 선택하거나 고유한 구성을 만들 수 있습니다.  원하는 구성을 선택하는 경우, 사용 가능한 옵션을 이해해야 합니다. 
---
= Azure에서 Cloud Volumes ONTAP 구성 계획
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure에 Cloud Volumes ONTAP 배포할 때 워크로드 요구 사항에 맞는 미리 구성된 시스템을 선택하거나 고유한 구성을 만들 수 있습니다.  원하는 구성을 선택하는 경우, 사용 가능한 옵션을 이해해야 합니다.



== Cloud Volumes ONTAP 라이선스를 선택하세요

Cloud Volumes ONTAP 에는 여러 가지 라이선싱 옵션이 제공됩니다. 각 옵션을 통해 귀하의 필요에 맞는 소비 모델을 선택할 수 있습니다.

* link:concept-licensing.html["Cloud Volumes ONTAP 에 대한 라이선싱 옵션에 대해 알아보세요"]
* link:task-set-up-licensing-azure.html["라이선싱 설정 방법 알아보기"]




== 지원되는 지역을 선택하세요

Cloud Volumes ONTAP 대부분의 Microsoft Azure 지역에서 지원됩니다. https://bluexp.netapp.com/cloud-volumes-global-regions["지원되는 지역의 전체 목록 보기"^] .



== 지원되는 VM 유형을 선택하세요

Cloud Volumes ONTAP 선택한 라이선스 유형에 따라 여러 VM 유형을 지원합니다.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Azure의 Cloud Volumes ONTAP 에 지원되는 구성"^]



== 저장 한도 이해하기

Cloud Volumes ONTAP 시스템의 원시 용량 제한은 라이선스에 따라 결정됩니다.  추가적인 제한은 골재와 부피의 크기에 영향을 미칩니다.  구성을 계획할 때 이러한 제한 사항을 알고 있어야 합니다.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-azure.html["Azure의 Cloud Volumes ONTAP 에 대한 저장소 한도"^]



== Azure에서 시스템 크기 조정

Cloud Volumes ONTAP 시스템의 크기를 조정하면 성능 및 용량 요구 사항을 충족하는 데 도움이 될 수 있습니다.  VM 유형, 디스크 유형 및 디스크 크기를 선택할 때 몇 가지 핵심 사항을 알아야 합니다.

가상 머신 유형:: 지원되는 가상 머신 유형을 살펴보세요. https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Cloud Volumes ONTAP 릴리스 노트"^] 그런 다음 지원되는 각 VM 유형에 대한 세부 정보를 검토합니다.  각 VM 유형은 특정 수의 데이터 디스크를 지원한다는 점을 알아두세요.
+
--
* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#dsv2-series["Azure 설명서: 범용 가상 머신 크기"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["Azure 설명서: 메모리 최적화된 가상 머신 크기"^]


--
단일 노드 시스템을 갖춘 Azure 디스크 유형:: Cloud Volumes ONTAP 에 대한 볼륨을 생성할 때 Cloud Volumes ONTAP 디스크로 사용하는 기본 클라우드 스토리지를 선택해야 합니다.
+
--
단일 노드 시스템은 다음 유형의 Azure Managed Disks를 사용할 수 있습니다.

* _프리미엄 SSD 관리 디스크_는 비용이 더 많이 들더라도 I/O 집약적 워크로드에 대해 높은 성능을 제공합니다.
* _프리미엄 SSD v2 관리형 디스크_는 프리미엄 SSD 관리형 디스크에 비해 더 낮은 비용으로 더 높은 성능과 더 낮은 지연 시간을 제공합니다.
* _표준 SSD 관리 디스크_는 낮은 IOPS가 필요한 작업 부하에 대해 일관된 성능을 제공합니다.
* _표준 HDD 관리 디스크_는 높은 IOPS가 필요하지 않고 비용을 절감하고 싶은 경우에 좋은 선택입니다.


이러한 디스크의 사용 사례에 대한 추가 세부 정보는 다음을 참조하세요. https://docs.microsoft.com/en-us/azure/virtual-machines/disks-types["Microsoft Azure 설명서: Azure에서 사용할 수 있는 디스크 유형은 무엇인가요?"^] .

--
HA 쌍이 있는 Azure 디스크 유형:: HA 시스템은 비용이 더 많이 들더라도 I/O 집약적 워크로드에 대해 높은 성능을 제공하는 프리미엄 SSD 공유 관리 디스크를 사용합니다.  9.12.1 릴리스 이전에 생성된 HA 배포는 프리미엄 페이지 Blob을 사용합니다.
Azure 디스크 크기::
+
--
Cloud Volumes ONTAP 인스턴스를 시작할 때 집계에 대한 기본 디스크 크기를 선택해야 합니다.  NetApp Console 초기 집계에 이 디스크 크기를 사용하고, 간단한 프로비저닝 옵션을 사용할 때 생성하는 추가 집계에도 이 디스크 크기를 사용합니다.  기본값과 다른 디스크 크기를 사용하는 집계를 생성할 수 있습니다.link:task-create-aggregates.html["고급 할당 옵션 사용"] .


TIP: 집계된 모든 디스크의 크기는 동일해야 합니다.

디스크 크기를 선택할 때는 여러 가지 요소를 고려해야 합니다.  디스크 크기는 스토리지 비용, 집계하여 생성할 수 있는 볼륨 크기, Cloud Volumes ONTAP 에서 사용할 수 있는 총 용량, 스토리지 성능에 영향을 미칩니다.

Azure Premium Storage의 성능은 디스크 크기에 따라 달라집니다.  더 큰 디스크는 더 높은 IOPS와 처리량을 제공합니다.  예를 들어, 1TiB 디스크를 선택하면 500GiB 디스크보다 비용이 더 많이 들더라도 더 나은 성능을 제공할 수 있습니다.

표준 저장소의 디스크 크기에는 성능 차이가 없습니다.  필요한 용량에 따라 디스크 크기를 선택해야 합니다.

디스크 크기별 IOPS 및 처리량은 Azure를 참조하세요.

* https://azure.microsoft.com/en-us/pricing/details/managed-disks/["Microsoft Azure: 관리 디스크 가격"^]
* https://azure.microsoft.com/en-us/pricing/details/storage/page-blobs/["Microsoft Azure: 페이지 Blob 가격 책정"^]


--




== 기본 시스템 디스크 보기

사용자 데이터 저장 외에도 콘솔은 Cloud Volumes ONTAP 시스템 데이터(부팅 데이터, 루트 데이터, 코어 데이터 및 NVRAM)를 위한 클라우드 스토리지도 구매합니다.  계획을 세우려면 Cloud Volumes ONTAP 배포하기 전에 이러한 세부 정보를 검토하는 것이 도움이 될 수 있습니다.

link:reference-default-configs.html#azure-single-node["Azure에서 Cloud Volumes ONTAP 시스템 데이터의 기본 디스크 보기"] .


TIP: 콘솔 에이전트에도 시스템 디스크가 필요합니다. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["콘솔 에이전트의 기본 구성에 대한 세부 정보 보기"^] .



== 네트워킹 정보 수집

Azure에 Cloud Volumes ONTAP 배포하는 경우 가상 네트워크에 대한 세부 정보를 지정해야 합니다.  워크시트를 사용하여 관리자로부터 정보를 수집할 수 있습니다.

[cols="30,70"]
|===
| Azure 정보 | 당신의 가치 


| 지역 |  


| 가상 네트워크(VNet) |  


| 서브넷 |  


| 네트워크 보안 그룹(자체 그룹 사용 시) |  
|===


== 쓰기 속도를 선택하세요

콘솔을 사용하면 Cloud Volumes ONTAP 에 대한 쓰기 속도 설정을 선택할 수 있습니다.  쓰기 속도를 선택하기 전에 일반 설정과 높은 설정의 차이점, 높은 쓰기 속도를 사용할 때의 위험과 권장 사항을 이해해야 합니다. link:concept-write-speed.html["쓰기 속도에 대해 자세히 알아보세요"] .



== 볼륨 사용 프로필을 선택하세요

ONTAP 에는 필요한 총 저장 용량을 줄일 수 있는 여러 가지 저장 효율성 기능이 포함되어 있습니다.  콘솔에서 볼륨을 생성할 때 이러한 기능을 활성화하는 프로필이나 비활성화하는 프로필을 선택할 수 있습니다.  어떤 프로필을 사용할지 결정하는 데 도움이 되도록 이러한 기능에 대해 자세히 알아보세요.

NetApp 스토리지 효율성 기능은 다음과 같은 이점을 제공합니다.

씬 프로비저닝:: 실제 물리적 스토리지 풀에 있는 것보다 더 많은 논리적 스토리지를 호스트나 사용자에게 제공합니다.  저장 공간을 미리 할당하는 대신, 데이터가 기록됨에 따라 각 볼륨에 저장 공간이 동적으로 할당됩니다.
중복제거:: 동일한 데이터 블록을 찾아 단일 공유 블록에 대한 참조로 대체하여 효율성을 향상시킵니다.  이 기술은 동일한 볼륨에 있는 중복된 데이터 블록을 제거하여 저장 용량 요구 사항을 줄입니다.
압축:: 1차, 2차, 보관 저장소의 볼륨 내 데이터를 압축하여 데이터를 저장하는 데 필요한 물리적 용량을 줄입니다.

