---
sidebar: sidebar 
permalink: task-setting-up-gcp-encryption.html 
keywords: encryption, gcp, encryption key, permissions, customer-managed, gcpencryption 
summary: Google Cloud Storage는 디스크에 쓰기 전에 항상 데이터를 암호화하지만, Console API를 사용하면 고객 관리 암호화 키를 사용하는 Cloud Volumes ONTAP 시스템을 만들 수 있습니다.  이러한 키는 Cloud Key Management Service를 사용하여 GCP에서 생성하고 관리하는 키입니다. 
---
= Cloud Volumes ONTAP 에서 고객 관리 암호화 키 사용
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud Storage는 디스크에 쓰기 전에 항상 데이터를 암호화하지만, API를 사용하면 _고객 관리 암호화 키_를 사용하는 Cloud Volumes ONTAP 시스템을 만들 수 있습니다.  이러한 키는 Cloud Key Management Service를 사용하여 GCP에서 생성하고 관리하는 키입니다.

.단계
. 키가 저장된 프로젝트에서 콘솔 에이전트 서비스 계정에 프로젝트 수준에서 올바른 권한이 있는지 확인하세요.
+
권한은 다음에서 제공됩니다. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["기본적으로 서비스 계정 권한"^] 하지만 Cloud Key Management Service에 대한 대체 프로젝트를 사용하는 경우에는 적용되지 않을 수 있습니다.

+
권한은 다음과 같습니다.

+
[source, yaml]
----
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
----
. 서비스 계정이 다음인지 확인하세요. https://cloud.google.com/iam/docs/service-agents["Google Compute Engine 서비스 에이전트"^] 키에 대한 Cloud KMS 암호화/복호화 권한이 있습니다.
+
서비스 계정의 이름은 "service-[service_project_number]@compute-system.iam.gserviceaccount.com" 형식을 사용합니다.

+
https://cloud.google.com/kms/docs/iam#granting_roles_on_a_resource["Google Cloud 문서: Cloud KMS와 함께 IAM 사용 - 리소스에 대한 역할 부여"]

. get 명령을 호출하여 키의 "id"를 얻으십시오. `/gcp/vsa/metadata/gcp-encryption-keys` API 호출 또는 GCP 콘솔의 키에서 "리소스 이름 복사"를 선택합니다.
. 고객 관리 암호화 키를 사용하고 데이터를 개체 스토리지로 계층화하는 경우 NetApp 콘솔은 영구 디스크를 암호화하는 데 사용되는 것과 동일한 키를 활용하려고 시도합니다.  하지만 먼저 Google Cloud Storage 버킷을 활성화하여 키를 사용해야 합니다.
+
.. 다음을 따라 Google Cloud Storage 서비스 에이전트를 찾으세요. https://cloud.google.com/storage/docs/getting-service-agent["Google Cloud 문서: Cloud Storage 서비스 에이전트 가져오기"^] .
.. 암호화 키로 이동하여 Google Cloud Storage 서비스 에이전트에 Cloud KMS 암호화/복호화 권한을 할당합니다.


+
자세한 내용은 다음을 참조하세요. https://cloud.google.com/storage/docs/encryption/using-customer-managed-keys["Google Cloud 문서: 고객 관리 암호화 키 사용"^]

. 시스템을 생성할 때 API 요청과 함께 "GcpEncryption" 매개변수를 사용하세요.
+
*예*

+
[source, json]
----
"gcpEncryptionParameters": {
    "key": "projects/project-1/locations/us-east4/keyRings/keyring-1/cryptoKeys/generatedkey1"
  }
----


를 참조하세요 https://docs.netapp.com/us-en/bluexp-automation/index.html["NetApp 콘솔 자동화 문서"^] "GcpEncryption" 매개변수 사용에 대한 자세한 내용은 다음을 참조하세요.
