---
sidebar: sidebar 
permalink: task-upgrade-disk-perf-azure.html 
keywords: azure, premium ssd v2, Premium SSDv2, performance parameters, cloud volumes ontap 
summary: Azure의 Premium SSD v2 디스크에서 성능 매개변수를 구성합니다. 
---
= Azure Cloud Volumes ONTAP 에서 프리미엄 SSD 디스크의 성능 계층을 변경합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure 포털을 사용하여 Azure의 Cloud Volumes ONTAP 에서 프리미엄 SSD 관리 디스크의 성능 등급을 업그레이드할 수 있습니다. 이는 각 프리미엄 SSD 디스크의 디스크 티어를 더 높은 성능 티어로 변경하는 수동 프로세스입니다. NVRAM 디스크의 성능 등급을 변경하면 더 높은 IOPS 및 처리량 기능을 제공하여 성능 병목 현상을 완화하고 Cloud Volumes ONTAP 시스템의 효율성을 향상시킬 수 있습니다.

.이 작업에 관하여
* Azure의 Cloud Volumes ONTAP 기본적으로 P20 계층에 NVRAM 용으로 프리미엄 SSD 디스크를 배포합니다. P20 등급은 대부분의 작업 부하에 적합한 균형 잡힌 성능을 제공합니다. 하지만 작업 부하에 더 높은 성능이 요구되는 경우 NVRAM 디스크를 P30과 같은 상위 등급으로 업그레이드할 수 있습니다.
+

TIP: 현재로서는 Azure 포털을 통해서만 NVRAM 디스크를 P20 티어에서 P30 티어로 업그레이드할 수 있습니다.

* 디스크 크기는 변경하지 않습니다. 용량은 여전히 512GB입니다. 이 절차는 디스크의 성능 등급만 변경합니다.


.시작하기 전에
* Cloud Volumes ONTAP 버전은 9.11.1 이상이어야 합니다. 하위 버전의 경우 9.11.1 이상 버전으로 업그레이드하거나 NetApp 지원팀에 기능 정책 변경 요청(FPVR)을 제출할 수 있습니다.
* NetApp 지원팀과 협력하여 환경에서 발생하는 병목 현상이 NVRAM 디스크 때문인지 확인하고, 티어 업그레이드를 통해 문제가 해결되는지 확인하십시오.
+

NOTE: NVRAM 디스크를 더 높은 성능 등급으로 업그레이드하면 추가 비용이 발생하므로 이러한 변경의 필요성을 신중하게 평가하는 것이 중요합니다.



.단계
이 시나리오는 노드가 두 개 있다고 가정합니다. `node01` 그리고 `node02` Cloud Volumes ONTAP 고가용성(HA) 배포에서. Azure 포털을 사용하여 티어를 업그레이드하세요.

. 만들기 위해 이 명령어를 실행하세요 `node1` 활성 노드. 수동 페일오버 `node02`.
+
`storage failover takeover -ofnode <Node02>`

. Azure Portal에 Sign in .
. 인수 작업이 완료되면 VM 인스턴스로 이동하세요. `node02`그리고 *정지* 버튼을 클릭하여 전원을 끄세요.
. 해당 리소스 그룹으로 이동하세요. `node02` 디스크 목록에서 티어를 변경할 NVRAM 디스크를 선택합니다.
. 크기와 성능을 모두 고려하여 선택하세요.
. *성능 등급* 드롭다운 메뉴에서 선택하세요. `P30 - 5000 IOPS, 200MB/s`.
. *크기 조정*을 선택하세요.
. 스위치를 켜세요 `node02` 사례.
. Azure 시리얼 콘솔에서 메시지가 표시될 때까지 확인하세요. `waiting for giveback`.
. 이 명령어를 실행하여 돌려주세요 `node02`:
+
`storage failover giveback -ofnode <Node02>`

. 다음 단계를 반복하세요. `node01` 만들다 `node02` 인수하다 `node01`이를 통해 NVRAM 디스크 계층을 업그레이드할 수 있습니다. `node01`.


.당신이 완료한 후
두 노드를 모두 켠 후에는 Azure 포털에서 Cloud Volumes ONTAP 시스템의 디스크 세부 정보를 확인하여 수정된 매개변수를 검증하십시오.

.관련 정보
* Azure 설명서: https://learn.microsoft.com/en-us/azure/virtual-machines/disks-performance-tiers?tabs=portal["다운타임 없이 성능 등급을 변경하세요"^]
* 지원팀을 위한 지식 기반: https://kb.netapp.com/Cloud/Azure_NetApp_Files/How_to_upgrade_performance_tier_of_NVRAM_disk_in_Azure_CVO["Azure CVO에서 NVRAM 디스크의 성능 계층을 업그레이드하는 방법"^]
* link:task-updating-ontap-cloud.html["Cloud Volumes ONTAP 소프트웨어 버전 업그레이드"]

