---
sidebar: sidebar 
permalink: task-improve-configurations-cvo.html 
keywords: improve configurations, optimize configurations, implement best practices, well-architected file system, Cloud Volumes ONTAP, Microsoft Azure 
summary: 잘 설계된 대시보드는 Cloud Volumes ONTAP 구성을 스캔하여 운영 우수성을 달성하는 데 도움이 되는 통찰력과 권장 사항을 제공합니다. 
---
= Workload Factory를 사용하여 Azure의 Cloud Volumes ONTAP 구성을 개선하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Console에서 NetApp Workload Factory를 사용하여 Azure의 Cloud Volumes ONTAP 시스템에 대한 모범 사례를 구현하십시오. 잘 설계된 상태를 쉽게 검토하고, 구성 문제에 대해 알아보고, 문제를 해결하여 안정성, 보안, 효율성, 성능 및 비용 측면에서 최적화되지 않은 시스템의 아키텍처를 개선할 수 있습니다.

link:concept-configuration-analysis-cvo.html["구성 분석 및 아키텍처 설계 상태에 대해 알아보세요."]



[[about-this-task]]
== 이 작업에 관하여

Workload Factory는 Microsoft Azure의 Cloud Volumes ONTAP 시스템 구성을 매일 분석합니다.

스토리지 구성 요구 사항은 다양하므로 스토리지 환경에 적용되지 않는 특정 구성의 분석을 제외할 수 있습니다.



[[before-you-begin]]
== 시작하기 전에

* Azure에 link:concept-azure-mktplace-direct.html["배포됨"] Cloud Volumes ONTAP 시스템이 있어야 아키텍처 상태 및 구성 문제에 대한 권장 사항을 볼 수 있습니다.
* Cloud Volumes ONTAP과 연결된 에이전트가 다음 엔드포인트에 액세스할 수 있는지 확인하십시오.
+
** \https://api.workloads.netapp.com
** \https://ws.workloads.bluexp.netapp.com






[[fix-a-configuration-issue]]
== 구성 문제 해결

Cloud Volumes ONTAP 시스템 또는 선택한 볼륨의 구성 문제를 해결합니다. 하나 이상의 구성을 선택하여 수정할 수 있습니다.

수정 작업으로 인해 인스턴스 다운타임이나 서비스 중단이 발생할 수 있습니다. 구성 문제를 수정하기 전에 각 권장 사항을 주의 깊게 검토하십시오.

.단계
. link:https://console.netapp.com/home["NetApp Console"^]에 로그인하십시오.
. NetApp Console 메뉴에서 *워크로드* > *잘 설계된 아키텍처* > *Azure용 Cloud Volumes ONTAP*을 선택합니다.
. Well-architected 대시보드에서 구성에 대해 *View and fix*를 선택합니다. 권장 사항을 꼼꼼히 검토하시기 바랍니다.
+
이 권장 사항은 모범 사례와 최적화되지 않은 구성의 잠재적 문제점을 설명합니다.

. 리소스를 선택한 다음 *Fix*를 클릭합니다.
+
일부 수정 사항은 특정 구성에서만 사용할 수 있으며 항상 둘 이상의 리소스에 적용할 수 있는 것은 아닙니다. 예를 들어, 단일 볼륨의 구성은 수정할 수 있지만 여러 볼륨의 구성은 수정할 수 없을 수도 있습니다.

. 인스턴스 다운타임이나 서비스 중단 등 이 수정 사항의 결과에 대해 알아보려면 조치 항목을 검토하십시오.
. Workload Factory에서 권장 변경 사항을 적용하려면 *Fix*를 선택하십시오.


.결과
Workload Factory에서 문제 해결 프로세스를 시작합니다.



[[dismiss-a-configuration-analysis]]
== 구성 분석 무시

Cloud Volumes ONTAP 시스템 또는 선택한 볼륨에 대한 구성 분석을 중지합니다. 필요에 따라 분석을 다시 시작할 수 있습니다.

[role="tabbed-block"]
====
.시스템에 대한 구성 분석 해제
--
.단계
. link:https://console.netapp.com/home["NetApp Console"^]에 로그인하십시오.
. NetApp Console 메뉴에서 *워크로드* > *잘 설계된 아키텍처* > *Azure용 Cloud Volumes ONTAP*을 선택합니다.
. 구성에서 사용자 환경에 적용되지 않는 구성을 찾은 다음 *닫기*를 선택합니다.
. 구성 분석을 중지하려면 [구성 해제] 대화 상자에서 [닫기]를 선택하십시오.


--
.볼륨에 대한 구성 분석 무시
--
.단계
. link:https://console.netapp.com/home["NetApp Console"^]에 로그인하십시오.
. NetApp Console 메뉴에서 *워크로드* > *잘 설계된 아키텍처* > *Azure용 Cloud Volumes ONTAP*을 선택합니다.
. 구성에서 리소스에 대해 해제할 구성을 확인한 다음 *보기 및 수정*을 선택합니다.
. 구성 페이지에서 구성 분석에서 제외할 리소스를 선택합니다.
+
** 하나의 리소스의 경우: 작업 메뉴를 선택한 다음 *볼륨 무시*를 선택합니다.
** 여러 리소스를 처리하려면 리소스를 선택한 다음 일괄 작업 옆에 있는 *해제*를 선택하십시오.


. 구성에 대한 분석을 중지하려면 *Dismiss* 를 선택합니다.
. 볼륨 닫기 대화 상자에서 *닫기*를 선택하여 확인합니다.


--
====
.결과
Workload Factory는 선택한 구성에 대한 구성 분석을 중지합니다.



[[reactivate-a-dismissed-configuration-analysis]]
== 해제된 구성 분석을 다시 활성화합니다

Cloud Volumes ONTAP 시스템에 대해 해제된 구성 분석을 언제든지 다시 활성화할 수 있습니다. 하나 이상의 구성을 선택하여 다시 활성화할 수 있습니다.

[role="tabbed-block"]
====
.시스템에 대한 구성 분석을 다시 활성화하십시오
--
.단계
. link:https://console.netapp.com/home["NetApp Console"^]에 로그인하십시오.
. NetApp Console 메뉴에서 *워크로드* > *잘 설계된 아키텍처* > *Azure용 Cloud Volumes ONTAP*을 선택합니다.
. *해제된 구성*을 선택합니다.
. 재활성화할 구성을 선택하고 *재활성화*를 선택하십시오.


--
.리소스에 대한 구성 분석 재활성화
--
.단계
. link:https://console.netapp.com/home["NetApp Console"^]에 로그인하십시오.
. NetApp Console 메뉴에서 *워크로드* > *잘 설계된 아키텍처* > *Azure용 Cloud Volumes ONTAP*을 선택합니다.
. *해제된 구성*을 선택합니다.
. 구성 페이지에서 다시 활성화할 리소스를 선택합니다.
+
** 하나의 리소스의 경우: 작업 메뉴를 선택한 다음 *다시 활성화*를 선택합니다.
** 여러 리소스를 처리하려면 리소스를 선택한 다음 일괄 작업 옆에 있는 *재활성화*를 선택하십시오.




--
====
.결과
Workload Factory는 구성 분석을 다시 활성화하고 매일 새로운 분석을 실행합니다.
