---
sidebar: sidebar 
permalink: task-planning-your-config.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, ec2, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, general purpose, gp2 provisioned IOPS, piops, throughput optimized, cold, SSD, HDD, st1, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported instances, instances, instances supported, supported ec2 instances, supported instance, aws outpost, outpost, outposts, deploy in outpost, deploy in aws outpost 
summary: AWS에 Cloud Volumes ONTAP 배포하는 경우 워크로드 요구 사항에 맞는 미리 구성된 시스템을 선택하거나 고유한 구성을 만들 수 있습니다.  원하는 구성을 선택하는 경우, 사용 가능한 옵션을 이해해야 합니다. 
---
= AWS에서 Cloud Volumes ONTAP 구성을 계획하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AWS에 Cloud Volumes ONTAP 배포하는 경우 워크로드 요구 사항에 맞는 미리 구성된 시스템을 선택하거나 고유한 구성을 만들 수 있습니다.  원하는 구성을 선택하는 경우, 사용 가능한 옵션을 이해해야 합니다.



== Cloud Volumes ONTAP 라이선스를 선택하세요

Cloud Volumes ONTAP 에는 여러 가지 라이선싱 옵션이 제공됩니다. 각 옵션을 통해 귀하의 필요에 맞는 소비 모델을 선택할 수 있습니다.

* link:concept-licensing.html["Cloud Volumes ONTAP 에 대한 라이선싱 옵션에 대해 알아보세요"]
* link:task-set-up-licensing-aws.html["라이선싱 설정 방법 알아보기"]




== 지원되는 지역을 선택하세요

Cloud Volumes ONTAP 대부분의 AWS 지역에서 지원됩니다. https://bluexp.netapp.com/cloud-volumes-global-regions["지원되는 지역의 전체 목록 보기"^] .

새로운 AWS 지역은 해당 지역에서 리소스를 생성하고 관리하기 전에 활성화해야 합니다. https://docs.aws.amazon.com/general/latest/gr/rande-manage.html["AWS 설명서: 리전을 활성화하는 방법 알아보기"^] .



=== 지원되는 로컬 영역을 선택하세요

로컬 존을 선택하는 것은 선택 사항입니다.  Cloud Volumes ONTAP 싱가포르를 포함한 일부 AWS 로컬 영역에서 지원됩니다.  AWS의 Cloud Volumes ONTAP 단일 가용성 영역에서만 고가용성(HA) 모드를 지원합니다.  단일 노드 배포는 지원되지 않습니다.


NOTE: Cloud Volumes ONTAP AWS 로컬 영역에서 데이터 계층화 및 클라우드 계층화를 지원하지 않습니다.  또한, Cloud Volumes ONTAP 에 적합하지 않은 인스턴스가 있는 로컬 영역은 지원되지 않습니다.  이에 대한 예가 마이애미인데, 지원되지 않고 적격하지 않은 Gen6 인스턴스만 있기 때문에 로컬 영역으로 사용할 수 없습니다.

link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/locations/?nc=sn&loc=3["AWS 문서: 로컬 영역 전체 목록 보기"^] . 로컬 영역을 활성화해야만 해당 영역에서 리소스를 만들고 관리할 수 있습니다.

link:https://docs.aws.amazon.com/local-zones/latest/ug/getting-started.html["AWS 설명서: AWS 로컬 영역 시작하기"^] .



== 지원되는 인스턴스를 선택하세요

Cloud Volumes ONTAP 선택한 라이선스 유형에 따라 여러 인스턴스 유형을 지원합니다.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["AWS의 Cloud Volumes ONTAP 에 지원되는 구성"^]



== 저장 한도 이해하기

Cloud Volumes ONTAP 시스템의 원시 용량 제한은 라이선스에 따라 결정됩니다.  추가적인 제한은 골재와 부피의 크기에 영향을 미칩니다.  구성을 계획할 때 이러한 제한 사항을 알고 있어야 합니다.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-aws.html["AWS의 Cloud Volumes ONTAP 대한 스토리지 한도"^]



== AWS에서 시스템 크기 조정

Cloud Volumes ONTAP 시스템의 크기를 조정하면 성능 및 용량 요구 사항을 충족하는 데 도움이 될 수 있습니다.  인스턴스 유형, 디스크 유형 및 디스크 크기를 선택할 때 몇 가지 핵심 사항을 알아야 합니다.

인스턴스 유형::
+
--
* 각 EC2 인스턴스 유형에 대한 최대 처리량 및 IOPS에 맞게 워크로드 요구 사항을 조정하세요.
* 여러 사용자가 동시에 시스템에 쓰는 경우 요청을 관리할 수 있는 충분한 CPU가 있는 인스턴스 유형을 선택하세요.
* 주로 읽기 작업을 하는 애플리케이션을 사용하는 경우, 충분한 RAM을 갖춘 시스템을 선택하세요.
+
** https://aws.amazon.com/ec2/instance-types/["AWS 설명서: Amazon EC2 인스턴스 유형"^]
** https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html["AWS 설명서: Amazon EBS 최적화 인스턴스"^]




--
EBS 디스크 유형:: 높은 수준에서 EBS 디스크 유형 간의 차이점은 다음과 같습니다.  EBS 디스크의 사용 사례에 대해 자세히 알아보려면 다음을 참조하세요. http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["AWS 문서: EBS 볼륨 유형"^] .
+
--
* _일반 용도 SSD(gp3)_ 디스크는 광범위한 작업 부하에 대해 비용과 성능의 균형을 맞춘 가장 저렴한 SSD입니다.  성능은 IOPS와 처리량으로 정의됩니다. gp3 디스크는 Cloud Volumes ONTAP 9.7 이상에서 지원됩니다.
+
gp3 디스크를 선택하면 NetApp 콘솔은 선택한 디스크 크기를 기준으로 gp2 디스크와 동등한 성능을 제공하는 기본 IOPS 및 처리량 값을 입력합니다. 더 높은 비용으로 더 나은 성능을 얻으려면 값을 늘릴 수 있지만, 낮은 값은 성능이 저하될 수 있으므로 지원하지 않습니다. 간단히 말해, 기본값을 고수하거나 기본값을 늘리세요. 낮추지 마세요. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html#gp3-ebs-volume-type["AWS 문서: gp3 디스크와 성능에 대해 자세히 알아보세요"^] .

+
Cloud Volumes ONTAP gp3 디스크를 사용하는 Amazon EBS Elastic Volumes 기능을 지원합니다. link:concept-aws-elastic-volumes.html["Elastic Volumes 지원에 대해 자세히 알아보세요"] .

* _일반 용도 SSD(gp2)_ 디스크는 광범위한 작업 부하에 대해 비용과 성능의 균형을 맞춥니다.  성능은 IOPS로 정의됩니다.
* _프로비저닝된 IOPS SSD(io1)_ 디스크는 더 높은 비용으로 최고의 성능을 필요로 하는 중요한 애플리케이션을 위한 것입니다.
+
Cloud Volumes ONTAP io1 디스크를 사용하여 Amazon EBS Elastic Volumes 기능을 지원합니다. link:concept-aws-elastic-volumes.html["Elastic Volumes 지원에 대해 자세히 알아보세요"] .

* _처리량 최적화 HDD(st1)_ 디스크는 저렴한 가격으로 빠르고 일관된 처리량이 필요한 자주 액세스되는 워크로드에 적합합니다.
+

NOTE: AWS 로컬 영역에서는 연결성이 부족하여 AWS S3에 대한 데이터 계층화를 사용할 수 없습니다.



--
EBS 디스크 크기:: 지원하지 않는 구성을 선택하는 경우link:concept-aws-elastic-volumes.html["Amazon EBS Elastic Volumes 기능"] 그러면 Cloud Volumes ONTAP 시스템을 시작할 때 초기 디스크 크기를 선택해야 합니다.  그 후에는 할 수 있습니다link:concept-storage-management.html["콘솔이 시스템 용량을 관리하도록 하세요"] , 하지만 당신이 원한다면link:task-create-aggregates.html["직접 집계를 생성하세요"] 다음 사항을 주의하세요.
+
--
* 집계된 모든 디스크의 크기는 동일해야 합니다.
* EBS 디스크의 성능은 디스크 크기에 따라 달라집니다.  크기는 SSD 디스크의 기준 IOPS와 최대 버스트 지속 시간을 결정하고, HDD 디스크의 기준 및 버스트 처리량을 결정합니다.
* 궁극적으로, 필요한 _지속적인 성능_을 제공하는 디스크 크기를 선택해야 합니다.
* 더 큰 디스크(예: 4TiB 디스크 6개)를 선택하더라도 EC2 인스턴스가 대역폭 제한에 도달할 수 있으므로 모든 IOPS를 얻지 못할 수 있습니다.
+
EBS 디스크 성능에 대한 자세한 내용은 다음을 참조하세요. http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["AWS 문서: EBS 볼륨 유형"^] .

+
위에서 언급한 대로 Amazon EBS Elastic Volumes 기능을 지원하는 Cloud Volumes ONTAP 구성에서는 디스크 크기를 선택할 수 없습니다. link:concept-aws-elastic-volumes.html["Elastic Volumes 지원에 대해 자세히 알아보세요"] .



--




== 기본 시스템 디스크 보기

사용자 데이터 저장 외에도 콘솔은 Cloud Volumes ONTAP 시스템 데이터(부팅 데이터, 루트 데이터, 코어 데이터 및 NVRAM)를 위한 클라우드 스토리지도 구매합니다.  계획을 세우려면 Cloud Volumes ONTAP 배포하기 전에 이러한 세부 정보를 검토하는 것이 도움이 될 수 있습니다.

link:reference-default-configs.html#aws["AWS에서 Cloud Volumes ONTAP 시스템 데이터의 기본 디스크 보기"] .


TIP: 콘솔 에이전트에도 시스템 디스크가 필요합니다. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["콘솔 에이전트의 기본 구성에 대한 세부 정보 보기"^] .



== AWS Outpost에 Cloud Volumes ONTAP 배포 준비

AWS Outpost가 있는 경우 배포 프로세스 중에 Outpost VPC를 선택하여 해당 Outpost에 Cloud Volumes ONTAP 배포할 수 있습니다. 경험은 AWS에 있는 다른 VPC와 동일합니다. 먼저 AWS Outpost에 콘솔 에이전트를 배포해야 합니다.

지적해야 할 몇 가지 제한 사항이 있습니다.

* 현재 단일 노드 Cloud Volumes ONTAP 시스템만 지원됩니다.
* Cloud Volumes ONTAP 과 함께 사용할 수 있는 EC2 인스턴스는 Outpost에서 사용 가능한 인스턴스로 제한됩니다.
* 현재는 일반용 SSD(gp2)만 지원됩니다.




== 네트워킹 정보 수집

AWS에서 Cloud Volumes ONTAP 시작할 때 VPC 네트워크에 대한 세부 정보를 지정해야 합니다.  워크시트를 사용하여 관리자로부터 정보를 수집할 수 있습니다.



=== 단일 AZ의 단일 노드 또는 HA 쌍

[cols="30,70"]
|===
| AWS 정보 | 당신의 가치 


| 지역 |  


| VPC |  


| 서브넷 |  


| 보안 그룹(자체 보안 그룹을 사용하는 경우) |  
|===


=== 여러 AZ의 HA 쌍

[cols="30,70"]
|===
| AWS 정보 | 당신의 가치 


| 지역 |  


| VPC |  


| 보안 그룹(자체 보안 그룹을 사용하는 경우) |  


| 노드 1 가용성 영역 |  


| 노드 1 서브넷 |  


| 노드 2 가용성 영역 |  


| 노드 2 서브넷 |  


| 중재자 가용성 영역 |  


| 중재자 서브넷 |  


| 중재자를 위한 키 쌍 |  


| 클러스터 관리 포트에 대한 유동 IP 주소 |  


| 노드 1의 데이터에 대한 플로팅 IP 주소 |  


| 노드 2의 데이터에 대한 플로팅 IP 주소 |  


| 플로팅 IP 주소에 대한 경로 테이블 |  
|===


== 쓰기 속도를 선택하세요

콘솔을 사용하면 Cloud Volumes ONTAP 에 대한 쓰기 속도 설정을 선택할 수 있습니다.  쓰기 속도를 선택하기 전에 일반 설정과 높은 설정의 차이점, 높은 쓰기 속도를 사용할 때의 위험과 권장 사항을 이해해야 합니다. link:concept-write-speed.html["쓰기 속도에 대해 자세히 알아보세요"] .



== 볼륨 사용 프로필을 선택하세요

ONTAP 에는 필요한 총 저장 용량을 줄일 수 있는 여러 가지 저장 효율성 기능이 포함되어 있습니다.  콘솔에서 볼륨을 생성할 때 이러한 기능을 활성화하는 프로필이나 비활성화하는 프로필을 선택할 수 있습니다.  어떤 프로필을 사용할지 결정하는 데 도움이 되도록 이러한 기능에 대해 자세히 알아보세요.

NetApp 스토리지 효율성 기능은 다음과 같은 이점을 제공합니다.

씬 프로비저닝:: 실제 물리적 스토리지 풀에 있는 것보다 더 많은 논리적 스토리지를 호스트나 사용자에게 제공합니다.  저장 공간을 미리 할당하는 대신, 데이터가 기록됨에 따라 각 볼륨에 저장 공간이 동적으로 할당됩니다.
중복제거:: 동일한 데이터 블록을 찾아 단일 공유 블록에 대한 참조로 대체하여 효율성을 향상시킵니다.  이 기술은 동일한 볼륨에 있는 중복된 데이터 블록을 제거하여 저장 용량 요구 사항을 줄입니다.
압축:: 1차, 2차, 보관 저장소의 볼륨 내 데이터를 압축하여 데이터를 저장하는 데 필요한 물리적 용량을 줄입니다.

