---
sidebar: sidebar 
permalink: task-deploy-cvo-azure-mktplc.html 
keywords: deploy cvo marketplace, marketplace direct cvo deployment, azure marketplace 
summary:  
---
= Azure Marketplace에서 Cloud Volumes ONTAP 배포
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure Marketplace 직접 배포를 사용하면 Cloud Volumes ONTAP 빠르고 쉽게 배포할 수 있습니다.  Azure 마켓플레이스에서 몇 번의 클릭만으로 Cloud Volumes ONTAP 빠르게 배포하고 사용자 환경에서 핵심 기능과 성능을 살펴볼 수 있습니다.

이 제안에 대한 자세한 내용은 다음을 참조하세요.link:concept-azure-mktplace-direct.html["NetApp Console 과 마켓플레이스에서 Cloud Volumes ONTAP 제품에 대해 알아보세요."] .

.이 작업에 관하여
Azure Marketplace 직접 배포를 사용하여 배포된 Cloud Volumes ONTAP 시스템은 다음과 같은 속성을 갖습니다.  Azure 마켓플레이스를 통해 배포된 독립 실행형 인스턴스의 기능은 NetApp Console 에서 검색될 때 변경됩니다.

* 최신 Cloud Volumes ONTAP 버전(9.16.1 이상).
* 프로비저닝 용량이 500GiB로 제한된 Cloud Volumes ONTAP 의 무료 라이선스입니다.  이 라이선스에는 NetApp 지원이 포함되지 않으며 만료 날짜도 없습니다.
* 단일 가용성 영역(AZ)에서 고가용성(HA) 모드로 구성된 두 개의 노드는 기본 일련 번호로 제공됩니다.  스토리지 가상 머신(스토리지 VM)은 다음에 배포됩니다.link:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["유연한 오케스트레이션 모드"] .
* 기본적으로 생성된 인스턴스에 대한 집계입니다.
* 500GiB 프로비저닝 용량의 프리미엄 SSD v2 관리 디스크와 루트 디스크, 데이터 디스크.
* NFS, CIFS, iSCSI 및 NVMe/TCP 데이터 서비스를 갖춘 하나의 데이터 저장 VM이 배포되었습니다.  추가 데이터 저장소 VM을 추가할 수 없습니다.
* NFS, CIFS(SMB), iSCSI, Autonomous Ransomware Protection(ARP), SnapLock 및 SnapMirror 대한 라이센스가 설치되었습니다.
* https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["ONTAP 온도 민감 저장 효율성(TSSE)"^], 볼륨 암호화 및 외부 키 관리가 기본적으로 활성화되어 있습니다.
* 다음 기능은 지원되지 않습니다.
+
** FabricPool 계층화
** 스토리지 VM 유형 변경
** 빠른 쓰기 모드




.시작하기 전에
* 유효한 Azure Marketplace 구독이 있는지 확인하세요.
* 네트워킹 요구 사항을 충족하는지 확인하세요.link:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["단일 AZ에 HA 배포"] Azure에서. link:reference-networking-azure.html["Cloud Volumes ONTAP 에 대한 Azure 네트워킹 설정"] .
* Cloud Volumes ONTAP 배포하려면 다음 Azure 역할 중 하나가 할당되어야 합니다.
+
** 그만큼 `contributor` 기본 권한이 있는 역할입니다. 자세한 내용은 다음을 참조하세요. https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Microsoft Azure 설명서: Azure 기본 제공 역할"^] .
** 다음 권한이 있는 사용자 지정 RBAC 역할입니다. 자세한 내용은 다음을 참조하세요. https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles["Azure 설명서: Azure 사용자 지정 역할"^] .
+
[]
====
"사용 권한": [ { "작업": [ "Microsoft.AAD/등록/작업", "Microsoft.Resources/구독/리소스그룹/쓰기", "Microsoft.Network/로드밸런서/쓰기", "Microsoft.ClassicCompute/virtualMachines/쓰기", "Microsoft.Compute/capacityReservationGroups/배포/작업", "Microsoft.ClassicCompute/virtualMachines/네트워크인터페이스/연관된네트워크보안그룹/쓰기", "Microsoft.Network/네트워크인터페이스/쓰기", "Microsoft.Compute/virtualMachines/쓰기", "Microsoft.Compute/virtualMachines/확장/쓰기", "Microsoft.Resources/배포/검증/작업", "Microsoft.Resources/구독/리소스그룹/읽기", "Microsoft.Network/virtualNetworks/쓰기", "Microsoft.Network/virtualNetworks/read", "Microsoft.Network/networkSecurityGroups/write", "Microsoft.Network/networkSecurityGroups/read", "Microsoft.Compute/disks/write", "Microsoft.Compute/virtualMachineScaleSets/write", "Microsoft.Resources/deployments/write", "Microsoft.Network/virtualNetworks/subnets/read", "Microsoft.Network/virtualNetworks/subnets/write" ], "notActions": [], "dataActions": [], "notDataActions": [] } ]

====
+

NOTE: 구독에 리소스 공급자 "Microsoft.storage"를 등록한 경우에는 필요하지 않습니다. `Microsoft.AAD/register/action` 허가. 자세한 내용은 다음을 참조하세요. https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/storage["Azure 설명서: 저장소에 대한 Azure 권한"^] .





.단계
. Azure Marketplace 사이트에서 NetApp 제품을 검색합니다.
. * NetApp Cloud Volumes ONTAP 직접*을 선택하세요.
. *만들기*를 클릭하여 배포 마법사를 시작합니다.
. 플랜을 선택하세요.  *계획* 목록에는 일반적으로 Cloud Volumes ONTAP 의 최신 릴리스가 표시됩니다.
. *기본* 탭에서 다음 세부 정보를 제공합니다.
+
** *구독*: 구독을 선택하세요.  배포는 구독 번호에 연결됩니다.
** *리소스 그룹*: 기존 리소스 그룹을 사용하거나 새 리소스 그룹을 만듭니다.  리소스 그룹은 Cloud Volumes ONTAP 시스템의 단일 그룹 내에서 디스크 및 스토리지 VM과 같은 모든 리소스를 할당하는 데 도움이 됩니다.
** *지역*: 단일 AZ에서 Azure HA 배포를 지원하는 지역을 선택하세요.  목록에서는 사용 가능한 지역만 볼 수 있습니다.
** *크기*: 지원되는 Premium SSD v2 관리 디스크에 대한 스토리지 VM 크기를 선택하세요.
** *지역*: 선택한 지역의 지역을 선택하세요.
** *관리자 비밀번호*: 비밀번호를 설정하세요.  배포 후 이 관리자 비밀번호를 사용하여 시스템에 로그인합니다.
** *비밀번호 확인*: 확인을 위해 동일한 비밀번호를 다시 입력하세요.
+
*** *네트워크* 탭에서 가상 네트워크와 서브넷을 추가하거나 목록에서 선택합니다.
+

NOTE: Microsoft Azure 제한 사항을 준수하려면 새 가상 네트워크를 설정할 때 새 서브넷을 만들어야 합니다.  마찬가지로, 기존 네트워크를 선택하는 경우 기존 서브넷을 선택해야 합니다.

*** 미리 정의된 네트워크 보안 그룹을 선택하려면 *예*를 선택하세요.  미리 정의된 Azure 네트워크 보안 그룹에 필요한 트래픽 규칙을 할당하려면 *아니요*를 선택합니다. 자세한 내용은 다음을 참조하세요. link:reference-networking-azure.html#security-group-rules["Azure에 대한 보안 그룹 규칙"] .
*** *고급* 탭에서 이 배포에 필요한 두 가지 Azure 기능이 설정되었는지 확인합니다. 참조하다link:task-saz-feature.html["Cloud Volumes ONTAP 단일 AZ 배포를 위한 Azure 기능 활성화"] 그리고link:task-azure-high-availability-mode.html["Azure에서 Cloud Volumes ONTAP 에 대해 고가용성 모드 활성화"] .
*** *태그* 탭에서 리소스 또는 리소스 그룹에 대한 이름과 값 쌍을 정의할 수 있습니다.
*** *검토 + 생성* 탭에서 세부 정보를 검토하고 배포를 시작합니다.






.당신이 완료한 후
배포 진행 상황을 보려면 알림 아이콘을 선택하세요.  Cloud Volumes ONTAP 이 배포되면 작업을 위해 나열된 스토리지 VM을 볼 수 있습니다.

접근이 가능해지면 ONTAP System Manager나 ONTAP CLI를 사용하여 설정한 관리자 자격 증명으로 스토리지 VM에 로그인합니다.  그 후에는 볼륨, LUN 또는 공유를 생성하고 Cloud Volumes ONTAP 의 스토리지 기능을 활용할 수 있습니다.



== 배포 문제 해결

Azure 마켓플레이스를 통해 직접 배포된 Cloud Volumes ONTAP 시스템에는 NetApp 의 지원이 포함되지 않습니다.  배포 중에 문제가 발생하면 독립적으로 문제를 해결하고 해결할 수 있습니다.

.단계
. Azure Marketplace 사이트에서 *부팅 진단 > 직렬 로그*로 이동합니다.
. 직렬 로그를 다운로드하고 조사하세요.
. 문제 해결을 위해서는 제품 설명서와 지식 기반(KB) 문서를 참조하세요.
+
** https://learn.microsoft.com/en-us/partner-center/["Azure 마켓플레이스 문서"]
** https://www.netapp.com/support-and-training/documentation/["NetApp 문서"]
** https://kb.netapp.com/["NetApp KB 문서"]






== 콘솔에서 배포된 시스템을 찾아보세요

Azure Marketplace 직접 배포를 사용하여 배포한 Cloud Volumes ONTAP 시스템을 검색하고 콘솔의 *시스템* 페이지에서 관리할 수 있습니다.  콘솔 에이전트는 시스템을 검색하고, 시스템을 추가하고, 필요한 라이선스를 적용하고, 이러한 시스템에 대해 콘솔의 모든 기능을 잠금 해제합니다.  PSSD v2 관리형 디스크가 있는 단일 AZ의 원래 HA 구성은 유지되며, 시스템은 원래 배포와 동일한 Azure 구독 및 리소스 그룹에 등록됩니다.

.이 작업에 관하여
Azure Marketplace 직접 배포를 사용하여 배포된 Cloud Volumes ONTAP 시스템을 검색하면 콘솔 에이전트는 다음 작업을 수행합니다.

* 발견된 시스템의 무료 라이센스를 일반적인 용량 기반으로 대체합니다.link:concept-licensing.html#packages["프리미엄 라이선스"] .
* 배포된 시스템의 기존 기능을 유지하고, 데이터 보호, 데이터 관리, 보안 기능 등 콘솔의 추가 기능을 추가합니다.
* 노드에 설치된 라이선스를 NFS, CIFS(SMB), iSCSI, ARP, SnapLock 및 SnapMirror 에 대한 새로운 ONTAP 라이선스로 교체합니다.
* 일반 노드 일련 번호를 고유한 일련 번호로 변환합니다.
* 필요에 따라 리소스에 새로운 시스템 태그를 할당합니다.
* 인스턴스의 동적 IP 주소를 정적 IP 주소로 변환합니다.
* 기능을 활성화합니다link:task-tiering.html["FabricPool 계층화"] ,link:task-verify-autosupport.html["AutoSupport"] , 그리고link:concept-worm.html["한 번 쓰고 여러 번 읽기"] 배포된 시스템에 (WORM) 저장소를 설치합니다.  필요할 때 콘솔에서 이러한 기능을 활성화할 수 있습니다.
* 인스턴스를 검색하는 데 사용된 NSS 계정에 인스턴스를 등록합니다.
* 용량 관리 기능을 활성화합니다.link:concept-storage-management.html#capacity-management["자동 및 수동 모드"] 발견된 시스템에 대해서.


.시작하기 전에
Azure Marketplace에서 배포가 완료되었는지 확인하세요.  콘솔 에이전트는 배포가 완료되고 검색이 가능한 경우에만 시스템을 검색할 수 있습니다.

.단계
콘솔에서는 기존 시스템을 검색하기 위한 표준 절차를 따릅니다. link:task-adding-systems.html["콘솔에 기존 Cloud Volumes ONTAP 시스템 추가"] .


CAUTION: 검색하는 동안 실패 메시지가 표시될 수 있지만 검색 프로세스가 완료될 때까지 무시할 수 있습니다. 검색 중에는 Azure Marketplace 포털에서 시스템 생성 Cloud Volumes ONTAP 구성, 특히 시스템 태그를 수정하지 마세요. 이러한 구성을 변경하면 예상치 못한 시스템 동작이 발생할 수 있습니다.

.당신이 완료한 후
검색이 완료되면 콘솔의 *시스템* 페이지에 나열된 시스템을 볼 수 있습니다.  다음과 같은 다양한 관리 작업을 수행할 수 있습니다.link:task-manage-aggregates.html["집계 확장"] ,link:task-create-volumes.html["볼륨 추가"] ,link:task-managing-svms-azure.html["추가 스토리지 VM 프로비저닝"] , 그리고link:task-change-azure-vm.html["인스턴스 유형 변경"] .

.관련 링크
저장소 생성에 대한 자세한 내용은 ONTAP 설명서를 참조하세요.

* https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["NFS용 볼륨 생성"^]
* https://docs.netapp.com/us-en/ontap-cli/lun-create.html["iSCSI에 대한 LUN 생성"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["CIFS에 대한 공유 생성"^]

