---
sidebar: sidebar 
permalink: task-planning-your-config-gcp.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported machine types, supported virtual machines, supported vms, supported instances 
summary: Cloud Volumes ONTAP 배포할 때 워크로드 요구 사항에 맞는 사전 구성된 시스템을 선택하거나 고유한 구성을 만들 수 있습니다.  원하는 구성을 선택하는 경우, 사용 가능한 옵션을 이해해야 합니다. 
---
= Google Cloud에서 Cloud Volumes ONTAP 구성을 계획하세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud에 Cloud Volumes ONTAP 배포하는 경우 워크로드 요구 사항에 맞는 미리 구성된 시스템을 선택하거나 고유한 구성을 만들 수 있습니다.  원하는 구성을 선택하는 경우, 사용 가능한 옵션을 이해해야 합니다.



== Cloud Volumes ONTAP 라이선스를 선택하세요

Cloud Volumes ONTAP 에는 여러 가지 라이선싱 옵션이 제공됩니다. 각 옵션을 통해 귀하의 필요에 맞는 소비 모델을 선택할 수 있습니다.

* link:concept-licensing.html["Cloud Volumes ONTAP 에 대한 라이선싱 옵션에 대해 알아보세요"]
* link:task-set-up-licensing-google.html["라이선싱 설정 방법 알아보기"]




== 지원되는 지역을 선택하세요

Cloud Volumes ONTAP 대부분의 Google Cloud 지역에서 지원됩니다. https://bluexp.netapp.com/cloud-volumes-global-regions["지원되는 지역의 전체 목록 보기"^] .



== 지원되는 머신 유형을 선택하세요

Cloud Volumes ONTAP 선택한 라이선스 유형에 따라 여러 가지 머신 유형을 지원합니다.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["GCP의 Cloud Volumes ONTAP 에 지원되는 구성"^]



== 저장 한도 이해하기

Cloud Volumes ONTAP 시스템의 원시 용량 제한은 라이선스에 따라 결정됩니다.  추가적인 제한은 골재와 부피의 크기에 영향을 미칩니다.  구성을 계획할 때 이러한 제한 사항을 알고 있어야 합니다.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-gcp.html["GCP의 Cloud Volumes ONTAP 대한 스토리지 한도"^]



== GCP에서 시스템 크기 조정

Cloud Volumes ONTAP 시스템의 크기를 조정하면 성능 및 용량 요구 사항을 충족하는 데 도움이 될 수 있습니다.  머신 유형, 디스크 유형 및 디스크 크기를 선택할 때 몇 가지 핵심 사항을 알아야 합니다.

기계 유형:: 지원되는 기계 유형을 확인하세요. https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Cloud Volumes ONTAP 릴리스 노트"^] 그런 다음 Google에서 지원되는 각 기기 유형에 대한 세부 정보를 검토합니다. 머신 유형에 맞는 vCPU 수와 메모리에 맞게 워크로드 요구 사항을 조정하세요. 각 CPU 코어가 네트워킹 성능을 향상시킨다는 점에 유의하세요.
+
--
자세한 내용은 다음을 참조하세요.

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Google Cloud 문서: N1 표준 머신 유형"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Google Cloud 문서: 성능"^]


--
GCP 디스크 유형:: Cloud Volumes ONTAP 에 대한 볼륨을 생성할 때 Cloud Volumes ONTAP 디스크에 사용하는 기본 클라우드 스토리지를 선택해야 합니다.  디스크 유형은 다음 중 하나일 수 있습니다.
+
--
* _영역별 SSD 영구 디스크_: SSD 영구 디스크는 높은 속도의 무작위 IOPS가 필요한 워크로드에 가장 적합합니다.
* _영역별 균형 지속 디스크_: 이러한 SSD는 GB당 더 낮은 IOPS를 제공하여 성능과 비용의 균형을 맞춥니다.
* _영역별 표준 영구 디스크_ : 표준 영구 디스크는 경제적이며 순차적 읽기/쓰기 작업을 처리할 수 있습니다.
+
자세한 내용은 다음을 참조하세요. https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud 문서: 영역별 영구 디스크(표준 및 SSD)"^] .



--
GCP 디스크 크기:: Cloud Volumes ONTAP 시스템을 배포할 때 초기 디스크 크기를 선택해야 합니다.  그 후에는 NetApp Console 사용하여 시스템 용량을 관리할 수 있지만 직접 집계를 구축하려는 경우 다음 사항에 유의하세요.
+
--
* 집계된 모든 디스크의 크기는 동일해야 합니다.
* 성능을 고려하면서 필요한 공간을 결정하세요.
* 영구 디스크의 성능은 디스크 크기와 시스템에서 사용 가능한 vCPU 수에 따라 자동으로 확장됩니다.
+
자세한 내용은 다음을 참조하세요.

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud 문서: 영역별 영구 디스크(표준 및 SSD)"^]
** https://cloud.google.com/compute/docs/disks/performance["Google Cloud 설명서: 영구 디스크 및 로컬 SSD 성능 최적화"^]




--




== 기본 시스템 디스크 보기

사용자 데이터 저장 외에도 콘솔은 Cloud Volumes ONTAP 시스템 데이터(부팅 데이터, 루트 데이터, 코어 데이터 및 NVRAM)를 위한 클라우드 스토리지도 구매합니다.  계획을 세우려면 Cloud Volumes ONTAP 배포하기 전에 이러한 세부 정보를 검토하는 것이 도움이 될 수 있습니다.

* link:reference-default-configs.html#google-cloud-single-node["Google Cloud에서 Cloud Volumes ONTAP 시스템 데이터의 기본 디스크 보기"] .
* https://docs.cloud.google.com/docs/quotas/overview["Google Cloud 문서: Cloud Quotas 개요"^]
+
Google Cloud Compute Engine은 리소스 사용에 할당량을 적용하므로 Cloud Volumes ONTAP 배포하기 전에 한도에 도달하지 않았는지 확인해야 합니다.




TIP: 콘솔 에이전트에도 시스템 디스크가 필요합니다. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["콘솔 에이전트의 기본 구성에 대한 세부 정보 보기"^] .



== 네트워킹 정보 수집

GCP에 Cloud Volumes ONTAP 배포하는 경우 가상 네트워크에 대한 세부 정보를 지정해야 합니다.  워크시트를 사용하여 관리자로부터 정보를 수집할 수 있습니다.

*단일 노드 시스템에 대한 네트워크 정보*

[cols="30,70"]
|===
| GCP 정보 | 당신의 가치 


| 지역 |  


| 존 |  


| VPC 네트워크 |  


| 서브넷 |  


| 방화벽 정책(자체 방화벽 정책을 사용하는 경우) |  
|===
*여러 영역의 HA 쌍에 대한 네트워크 정보*

[cols="30,70"]
|===
| GCP 정보 | 당신의 가치 


| 지역 |  


| 노드 1의 영역 |  


| 노드 2의 영역 |  


| 중재자를 위한 구역 |  


| VPC-0 및 서브넷 |  


| VPC-1 및 서브넷 |  


| VPC-2 및 서브넷 |  


| VPC-3 및 서브넷 |  


| 방화벽 정책(자체 방화벽 정책을 사용하는 경우) |  
|===
*단일 존의 HA 쌍에 대한 네트워크 정보*

[cols="30,70"]
|===
| GCP 정보 | 당신의 가치 


| 지역 |  


| 존 |  


| VPC-0 및 서브넷 |  


| VPC-1 및 서브넷 |  


| VPC-2 및 서브넷 |  


| VPC-3 및 서브넷 |  


| 방화벽 정책(자체 방화벽 정책을 사용하는 경우) |  
|===


== 쓰기 속도를 선택하세요

콘솔을 사용하면 Google Cloud의 고가용성(HA) 쌍을 제외하고 Cloud Volumes ONTAP 에 대한 쓰기 속도 설정을 선택할 수 있습니다.  쓰기 속도를 선택하기 전에 일반 설정과 높은 설정의 차이점, 높은 쓰기 속도를 사용할 때의 위험과 권장 사항을 이해해야 합니다. link:concept-write-speed.html["쓰기 속도에 대해 자세히 알아보세요"] .



== 볼륨 사용 프로필을 선택하세요

ONTAP 에는 필요한 총 저장 용량을 줄일 수 있는 여러 가지 저장 효율성 기능이 포함되어 있습니다.  콘솔에서 볼륨을 생성할 때 이러한 기능을 활성화하는 프로필이나 비활성화하는 프로필을 선택할 수 있습니다.  어떤 프로필을 사용할지 결정하는 데 도움이 되도록 이러한 기능에 대해 자세히 알아보세요.

NetApp 스토리지 효율성 기능은 다음과 같은 이점을 제공합니다.

씬 프로비저닝:: 실제 물리적 스토리지 풀에 있는 것보다 더 많은 논리적 스토리지를 호스트나 사용자에게 제공합니다.  저장 공간을 미리 할당하는 대신, 데이터가 기록됨에 따라 각 볼륨에 저장 공간이 동적으로 할당됩니다.
중복제거:: 동일한 데이터 블록을 찾아 단일 공유 블록에 대한 참조로 대체하여 효율성을 향상시킵니다.  이 기술은 동일한 볼륨에 있는 중복된 데이터 블록을 제거하여 저장 용량 요구 사항을 줄입니다.
압축:: 1차, 2차, 보관 저장소의 볼륨 내 데이터를 압축하여 데이터를 저장하는 데 필요한 물리적 용량을 줄입니다.

