---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport 시스템 상태를 사전에 모니터링하고 NetApp 기술 지원팀에 메시지를 전송합니다.  기본적으로 AutoSupport 각 노드에서 HTTPS 전송 프로토콜을 사용하여 기술 지원팀에 메시지를 보낼 수 있도록 활성화되어 있습니다.  AutoSupport 이러한 메시지를 보낼 수 있는지 확인하는 것이 가장 좋습니다. 
---
= Cloud Volumes ONTAP 에 대한 AutoSupport 설정 확인
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport 시스템 상태를 사전에 모니터링하고 NetApp 기술 지원팀에 메시지를 전송합니다.  기본적으로 AutoSupport 각 노드에서 HTTPS 전송 프로토콜을 사용하여 기술 지원팀에 메시지를 보낼 수 있도록 활성화되어 있습니다.  AutoSupport 이러한 메시지를 보낼 수 있는지 확인하는 것이 가장 좋습니다.

유일하게 필요한 구성 단계는 Cloud Volumes ONTAP 아웃바운드 인터넷 연결이 있는지 확인하는 것입니다.  자세한 내용은 클라우드 제공업체의 네트워킹 요구 사항을 참조하세요.



== AutoSupport 요구 사항

Cloud Volumes ONTAP 노드에는 NetApp AutoSupport 에 대한 아웃바운드 인터넷 액세스가 필요합니다. NetApp AutoSupport는 시스템 상태를 사전에 모니터링하고 NetApp 기술 지원팀에 메시지를 전송합니다.

라우팅 및 방화벽 정책은 Cloud Volumes ONTAP AutoSupport 메시지를 보낼 수 있도록 다음 엔드포인트에 대한 HTTPS 트래픽을 허용해야 합니다.

* \ https://mysupport.netapp.com/aods/asupmessage
* \ https://mysupport.netapp.com/asupprod/post/1.0/postAsup


AutoSupport 메시지를 보내기 위한 아웃바운드 인터넷 연결이 불가능한 경우 NetApp Console Cloud Volumes ONTAP 시스템이 콘솔 에이전트를 프록시 서버로 사용하도록 자동으로 구성합니다.  유일한 요구 사항은 콘솔 에이전트의 보안 그룹이 포트 3128을 통한 _인바운드_ 연결을 허용하는 것입니다. 콘솔 에이전트를 배포한 후 이 포트를 열어야 합니다.

Cloud Volumes ONTAP 에 대해 엄격한 아웃바운드 규칙을 정의한 경우 Cloud Volumes ONTAP 보안 그룹이 포트 3128을 통한 _아웃바운드_ 연결을 허용하는지 확인해야 합니다.


TIP: HA 쌍을 사용하는 경우 HA 중재자는 아웃바운드 인터넷 액세스가 필요하지 않습니다.

아웃바운드 인터넷 접속이 가능한지 확인한 후 AutoSupport 메시지를 보낼 수 있는지 테스트할 수 있습니다.  지침은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["ONTAP 설명서: AutoSupport 설정"^] .



== AutoSupport 구성 문제 해결

외부 연결이 불가능하고 콘솔에서 Cloud Volumes ONTAP 시스템을 콘솔 에이전트를 프록시 서버로 사용하도록 구성할 수 없는 경우, 시스템에서 AutoSupport 메시지를 보낼 수 없다는 알림이 콘솔에서 표시됩니다. 이 문제를 해결하려면 다음 단계를 따르십시오.

.단계
. ONTAP CLI를 사용하려면 SSH를 사용하여 Cloud Volumes ONTAP 시스템에 안전하게 연결하십시오.
+
link:task-connecting-to-otc.html["Cloud Volumes ONTAP 에 SSH하는 방법 알아보기"] .

. AutoSupport 하위 시스템의 자세한 상태를 확인하십시오.
+
`autosupport check show-details`

+
응답은 다음과 같습니다.

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
http-https 카테고리의 상태가 다음과 같으면 `OK` 이는 AutoSupport 제대로 구성되어 메시지를 보낼 수 있음을 의미합니다.

. 그렇지 않다면 각 Cloud Volumes ONTAP 노드의 프록시 URL을 확인하십시오.
+
`autosupport show -fields proxy-url`

. 프록시 URL 매개변수가 비어 있으면 Cloud Volumes ONTAP 구성하여 콘솔 에이전트를 프록시로 사용합니다.
+
`autosupport modify -proxy-url \http://<console agent private ip>:3128`

. AutoSupport 상태를 다시 확인하십시오.
+
`autosupport check show-details`

. 상태가 여전히 실패로 표시되는 경우, Cloud Volumes ONTAP 과 콘솔 에이전트 간에 포트를 통해 연결이 제대로 되어 있는지 확인하십시오. `3128`.
. 확인 후에도 상태가 여전히 실패로 표시되면 콘솔 에이전트에 SSH로 접속하십시오.
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#connect-to-the-linux-vm["콘솔 에이전트를 위한 Linux VM 연결에 대해 자세히 알아보세요."^]

. 가다 `/opt/application/netapp/cloudmanager/docker_occm/data/`.
. 프록시 구성 파일을 엽니다. `squid.conf`. 파일의 구조는 다음과 같습니다.
+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        http_access allow netapp_support
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on
----
. 파일에 Cloud Volumes ONTAP 시스템의 CIDR 블록에 대한 항목이 없는 경우 새 항목을 추가하고 액세스를 허용하십시오.
+
`acl cvonet src <cidr>`

+
`http_access allow cvonet`

+
예를 들면 다음과 같습니다.

+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        acl cvonet src <cidr>
        http_access allow netapp_support
        http_access allow cvonet
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on

----
. 설정 파일을 편집한 후 프록시 컨테이너를 다시 시작하십시오. `sudo`. 그런 다음 Docker 또는 Podman을 사용하는지에 따라 다음 명령을 실행하세요.
+
Docker의 경우, 다음 명령을 실행하세요. `docker restart squid`.

+
Podman을 사용 중이라면 다음 명령을 실행하세요. `podman restart squid`.

. ONTAP CLI로 돌아가서 Cloud Volumes ONTAP AutoSupport 메시지를 보낼 수 있는지 확인하십시오.
+
`autosupport check show-details`



.관련 링크
* link:reference-networking-aws.html["AWS의 Cloud Volumes ONTAP 에 대한 네트워킹 요구 사항"^]
* link:reference-networking-azure.html["Azure에서 Cloud Volumes ONTAP 의 네트워킹 요구 사항"^]
* link:reference-networking-gcp.html["Google Cloud에서 Cloud Volumes ONTAP 사용하기 위한 네트워킹 요구 사항"^]

