---
sidebar: sidebar 
permalink: task-encrypting-volumes.html 
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption 
summary: 'Cloud Volumes ONTAP 외부 키 관리자를 사용하여 NetApp 볼륨 암호화(NVE)와 NetApp 집계 암호화(NAE)를 모두 지원합니다.  외부 키 관리자를 설정하면 NVE와 NAE가 기본적으로 활성화됩니다.' 
---
= NetApp 암호화 솔루션을 사용하여 Cloud Volumes ONTAP 에서 볼륨 암호화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP NetApp Volume Encryption(NVE)과 NetApp Aggregate Encryption(NAE)을 지원합니다.  NVE와 NAE는 볼륨의 FIPS 140-2 호환 저장 데이터 암호화를 지원하는 소프트웨어 기반 솔루션입니다. link:concept-security.html["이러한 암호화 솔루션에 대해 자세히 알아보세요"] .

NVE와 NAE는 모두 외부 키 관리자를 통해 지원됩니다.

NVE를 사용하는 경우 클라우드 공급자의 키 보관소를 사용하여 ONTAP 암호화 키를 보호하는 옵션이 있습니다.

* AWS Key Management Service(9.12.0 버전부터 지원)
* Azure 키 보관소(AKV)
* Google Cloud 키 관리 서비스


외부 키 관리자를 설정한 후에는 새 애그리게이트에 기본적으로 NAE가 활성화됩니다. NAE 애그리게이트에 속하지 않는 새 볼륨에는 기본적으로 NVE가 활성화됩니다(예: 외부 키 관리자를 설정하기 전에 생성된 기존 애그리게이트가 있는 경우).

Cloud Volumes ONTAP는 온보드 키 관리를 지원하지 않습니다.

.시작하기 전에
Cloud Volumes ONTAP 시스템을 NetApp 지원팀에 등록해야 합니다. NetApp 볼륨 암호화 라이선스는 NetApp 지원팀에 등록된 각 Cloud Volumes ONTAP 시스템에 자동으로 설치됩니다.

* https://docs.netapp.com/us-en/console-setup-admin/task-adding-nss-accounts.html["콘솔에 NetApp 지원 사이트 계정 추가"^]
* link:task-registering.html["선불 시스템 등록"]



NOTE: NetApp 콘솔은 중국 지역에 있는 시스템에 NVE 라이선스를 설치하지 않습니다.

.단계
. 지원되는 키 관리자 목록을 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 도구"^]에서 검토하십시오.
+

TIP: *Key Managers* 솔루션을 검색합니다.

. link:task-connecting-to-otc.html["Cloud Volumes ONTAP CLI에 연결"^].
. 외부 키 관리를 구성합니다.
+
** AWS: link:task-aws-key-management.html["AWS 키 관리 서비스"]
** Azure: link:task-azure-key-vault.html["Azure 키 보관소(AKV)"]
** Google Cloud: link:task-google-key-manager.html["Google Cloud 키 관리 서비스"]



