= BlueXP 에서 System Manager에 액세스하기 위해 사용자 인증이 활성화되었습니다.
:allow-uri-read: 




=== BlueXP 에서 System Manager에 액세스하기 위해 사용자 인증이 활성화되었습니다.

BlueXP 관리자는 이제 BlueXP 에서 ONTAP System Manager에 액세스하는 ONTAP 사용자에 대한 인증을 활성화할 수 있습니다.  BlueXP Connector 설정을 편집하면 이 옵션을 활성화할 수 있습니다.  이 옵션은 표준 모드와 개인 모드에서 사용할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-administer-advanced-view.html["System Manager를 사용하여 Cloud Volumes ONTAP 관리"^] .



=== BlueXP Advanced View가 System Manager로 이름이 변경되었습니다.

ONTAP System Manager를 통한 BlueXP 의 Cloud Volumes ONTAP 고급 관리 옵션의 이름이 *고급 보기*에서 *시스템 관리자*로 변경되었습니다.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-administer-advanced-view.html["System Manager를 사용하여 Cloud Volumes ONTAP 관리"^] .



=== BlueXP digital wallet 사용하여 라이선스를 관리하는 더 간단한 방법을 소개합니다.

이제 BlueXP digital wallet 내의 개선된 탐색 포인트를 사용하여 Cloud Volumes ONTAP 라이선스를 더욱 간편하게 관리할 수 있습니다.

* *관리 > 라이선스 및 구독 > 개요/직접 라이선스* 탭을 통해 Cloud Volumes ONTAP 라이선스 정보에 쉽게 액세스할 수 있습니다.
* *개요* 탭의 Cloud Volume ONTAP 패널에서 *보기*를 클릭하면 용량 기반 라이선스에 대한 포괄적인 정보를 얻을 수 있습니다.  이 고급 보기는 라이선스와 구독에 대한 자세한 정보를 제공합니다.
* 이전 인터페이스를 선호하는 경우 *레거시 보기로 전환* 버튼을 클릭하면 라이선스 유형별 세부 정보를 보고 라이선스에 대한 청구 방법을 수정할 수 있습니다.


link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html["용량 기반 라이선스 관리"^] .
