= Azure에서 Premium SSD v2 디스크의 성능을 향상시킬 수 있는 기능
:allow-uri-read: 




=== Azure에서 Premium SSD v2 디스크의 성능을 향상시킬 수 있는 기능

이제 Azure에서 Premium SSD v2 관리형 디스크의 성능을 IOPS 및 처리량 매개변수를 수정하여 향상시킬 수 있습니다.  이 기능을 사용하면 워크로드 요구 사항에 따라 시스템의 스토리지 성능을 최적화할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-perf-params-azure.html["Azure Cloud Volumes ONTAP 에서 Premium SSD v2 디스크 성능을 관리하세요."^].



=== Essentials 라이선스 초과 사용 요금 청구 방식 간소화

Cloud Volumes ONTAP 마켓플레이스 연간 계약/프라이빗 오퍼의 경우, Essentials 라이선스 초과 사용량 계산 방식이 이제 BYOL(Bring Your Own License) 패키지와 동일하게 적용됩니다.  이전에는 초과 사용량에 대해 동일한 Essentials 패키지에 대한 시간당 시장 요율로 청구되었습니다.  만약 마켓플레이스 연간 계약에 여러 Essentials 패키지가 포함되어 있다면, NetApp Console 구독에 포함된 더 비싼 Essentials 패키지의 사용 가능한 용량을 기준으로 해당 Essentials 패키지의 초과 사용량을 청구합니다.  이를 통해 Essentials 패키지의 초과 사용량 계산이 간소화되고 BYOL 라이선스에서 구독 기반 모델로의 원활한 전환이 보장됩니다.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Essentials 라이선스 초과 사용 요금 부과 방식"^]



=== Azure Edsv6 크기 시리즈 지원

Cloud Volumes ONTAP 9.17.1 버전부터 NetApp Console 통해 새로운 Cloud Volumes ONTAP 인스턴스에 Azure Edsv6 시리즈 VM을 배포할 수 있습니다.  Cloud Volumes ONTAP 9.17.1 이상 버전에서는 신규 배포 시 2세대 VM만 지원합니다.  이러한 2세대 장비는 UEFI(Unified Extensible Firmware Interface), Azure Boost 시스템 및 NVMe와 같은 최신 기술과 호환됩니다.  이러한 스토리지 시스템은 데이터베이스 서버 및 분석 엔진과 같이 빠른 로컬 스토리지가 필요한 메모리 집약적인 시스템 및 애플리케이션에 이상적입니다.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Azure의 Cloud Volumes ONTAP 에 지원되는 구성"^]
