= Cloud Volumes ONTAP과 Microsoft OneLake 통합
:allow-uri-read: 




[[cloud-volumes-ontap-integration-with-microsoft-onelake]]
=== Cloud Volumes ONTAP과 Microsoft OneLake 통합

Cloud Volumes ONTAP이 이제 공개 미리 보기로  https://learn.microsoft.com/en-us/fabric/onelake/onelake-overview["Microsoft OneLake"^]와의 통합을 지원합니다. Cloud Volumes ONTAP을  https://community.fabric.microsoft.com/["Microsoft Fabric"^]와  https://learn.microsoft.com/en-us/fabric/onelake/onelake-overview["Microsoft OneLake"^]을 사용하여 통합하면 기존 Cloud Volumes ONTAP NAS 데이터를 Power BI, Azure AI Search, OpenAI 및 Microsoft Copilot 등 Microsoft 분석 및 AI 서비스에서 사용할 수 있습니다. 이 통합에는 데이터 이동이나 중복이 필요하지 않습니다. 이 통합은  https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html["ONTAP S3 멀티 프로토콜"^] 액세스를 사용하여 Cloud Volumes ONTAP을 기존 Microsoft Fabric 레이크하우스에 연결합니다.

.관련 기사 및 자료:
* https://www.netapp.com/blog/optimize-ai-analytics-microsoft-onelake/?utm_content=nativelink&utm_medium=internal&utm_source=linkedin&utm_campaign=b2d-port-all-na-ww-digi-blog-1747859361262&es_id=956c739202["NetApp 블로그: Microsoft OneLake 및 NetApp Cloud Volumes ONTAP로 AI 및 분석 최적화"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-azure-onelake.html["AI 및 분석을 위해 Cloud Volumes ONTAP 시스템을 Microsoft OneLake와 통합"^]
* https://www.netapp.com/media/160786-na-1263-netapp-cloud-volumes-ontap-azure-onelake.pdf["Cloud Volumes ONTAP과 Microsoft OneLake 통합 - 기술 개요"^]




[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Microsoft Azure의 Cloud Volumes ONTAP 구성 수정, 해제 및 재활성화

NetApp Console의 잘 설계된 대시보드를 통해 이제 Cloud Volumes ONTAP 시스템에 대한 구성 권장 사항을 수정할 수 있습니다.

또한, 아키텍처 분석에서 하나 이상의 구성을 제외할 수 있습니다. 이를 통해 사용자 환경에 적용되지 않는 특정 구성을 무시할 수 있습니다.

나중에 해제된 구성을 포함하려면 잘 설계된 대시보드에서 다시 활성화할 수 있습니다. 이렇게 하면 구성이 분석에 복원되어 권장 사항 및 수정 사항을 확인할 수 있습니다.

* link:https://docs.netapp.com/us-en/console-well-architected/cvo/improve-configurations-cvo.html["Microsoft Azure의 Cloud Volumes ONTAP 구성 수정, 해제 및 재활성화"^]

